import js from '@eslint/js';
import tsPlugin from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import importPlugin from 'eslint-plugin-import';
import globals from 'globals';

export default [
  // Ignore patterns (migrated from .eslintignore)
  {
    ignores: [
      'dist/**',
      'build/**',
      'node_modules/**',
      '*.config.js',
      '*.config.ts',
      'src-tauri/**', // Rust source directory
      'public/**',
      'coverage/**',
      '.tauri/**',
      'e2e-results/**',
      'playwright-report/**',
      'src/lib/bindings.ts', // generated by Specta; checked via bindings:check + tsc
    ],
  },

  // Base recommended configs
  js.configs.recommended,

  // Main TypeScript/React configuration
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        project: './tsconfig.json',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.node,
        // Web Crypto API
        crypto: 'readonly',
        // React globals
        React: 'readonly',
        JSX: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
      'react': reactPlugin,
      'react-hooks': reactHooksPlugin,
      'import': importPlugin,
    },
    settings: {
      react: {
        version: 'detect',
      },
      'import/parsers': {
        '@typescript-eslint/parser': ['.ts', '.tsx'],
      },
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
          project: './tsconfig.json',
        },
      },
    },
    rules: {
      // ===================================
      // Core ESLint Rules
      // ===================================
      'no-console': 'off', // Allow console in development, will be stripped in production
      'no-debugger': 'warn',
      'no-unused-vars': 'off', // Disabled in favor of TypeScript rule
      'no-undef': 'off', // TypeScript handles this
      'no-redeclare': 'off', // TypeScript handles this for enums/types
      'prefer-const': 'error',
      'no-var': 'error',
      'object-shorthand': ['error', 'always'],
      'quote-props': ['error', 'as-needed'],
      'prefer-template': 'error',
      'prefer-arrow-callback': 'error',
      'arrow-body-style': ['error', 'as-needed'],
      'eqeqeq': ['error', 'always', { null: 'ignore' }],
      'no-nested-ternary': 'off', // Temporarily disabled - 37 warnings

      // ===================================
      // TypeScript Rules
      // ===================================
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off', // Too many warnings, TypeScript infers types well
      '@typescript-eslint/no-floating-promises': 'off', // Temporarily disabled - too many to fix now (58 warnings)
      '@typescript-eslint/await-thenable': 'warn',
      '@typescript-eslint/no-misused-promises': 'off', // Temporarily disabled - too many to fix now (65 warnings),
      '@typescript-eslint/prefer-nullish-coalescing': 'off', // Too many false positives
      '@typescript-eslint/prefer-optional-chain': 'warn',
      '@typescript-eslint/consistent-type-imports': 'off', // Conflicts with some TypeScript patterns
      '@typescript-eslint/naming-convention': [
        'warn', // Changed to warn to allow generated code
        {
          selector: 'typeLike',
          format: ['PascalCase'],
        },
        {
          selector: 'interface',
          format: ['PascalCase'],
          custom: {
            regex: '^I[A-Z]',
            match: false,
          },
        },
      ],

      // ===================================
      // React Rules
      // ===================================
      'react/react-in-jsx-scope': 'off', // Not needed in React 17+
      'react/prop-types': 'off', // Using TypeScript
      'react/jsx-uses-react': 'off',
      'react/jsx-uses-vars': 'error',
      'react/jsx-key': ['error', { checkFragmentShorthand: true }],
      'react/jsx-no-target-blank': 'error',
      'react/jsx-curly-brace-presence': ['error', { props: 'never', children: 'never' }],
      'react/self-closing-comp': 'error',
      'react/jsx-boolean-value': ['error', 'never'],

      // ===================================
      // React Hooks Rules
      // ===================================
      'react-hooks/rules-of-hooks': 'warn', // Some utility functions use hooks pattern
      'react-hooks/exhaustive-deps': 'warn',

      // ===================================
      // Import Rules
      // ===================================
      // The UI has deliberate lowercase compatibility modules next to legacy
      // PascalCase component directories (button.tsx/Button, etc.). Resolve
      // exact imports without treating macOS case folding as a missing path.
      'import/no-unresolved': ['error', { caseSensitive: false }],
      'import/no-cycle': 'error',
      'import/no-self-import': 'error',
      'import/no-duplicates': 'error',
      'import/first': 'error',
      'import/newline-after-import': 'error',

      // Block direct invoke() imports - must use VaultAPI
      // TODO: Re-enable after migrating all invoke() calls to VaultAPI
      /*
      'no-restricted-imports': ['error', {
        patterns: [{
          group: ['@tauri-apps/api/core'],
          importNames: ['invoke'],
          message: 'Direct invoke() calls are prohibited. Use VaultAPI from @/lib/api instead.\n\n' +
            'Example:\n' +
            '  ❌ import { invoke } from \'@tauri-apps/api/core\';\n' +
            '  ✅ import { vaultApi } from \'@/lib/api\';\n\n' +
            'See CONTRIBUTING.md for the IPC conventions.'
        }]
      }],
      */

      'import/order': [
        'error',
        {
          groups: [
            'builtin',
            'external',
            'internal',
            ['parent', 'sibling', 'index'],
            'type',
          ],
          'newlines-between': 'always',
          alphabetize: {
            order: 'asc',
            caseInsensitive: true,
          },
          pathGroups: [
            {
              pattern: 'react',
              group: 'external',
              position: 'before',
            },
            {
              pattern: '@/**',
              group: 'internal',
              position: 'before',
            },
          ],
          pathGroupsExcludedImportTypes: ['react'],
        },
      ],

      // ===================================
      // Design System Enforcement Rules
      // ===================================
      // Temporarily disabled to get tests passing - should be re-enabled after design tokens are implemented
      /*
      'no-restricted-syntax': [
        'error',
        // Background colors
        {
          selector: 'JSXAttribute[name.name="className"] Literal[value=/bg-(white|black|gray|slate|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\\d+/]',
          message:
            'Hardcoded background color detected. Use CSS variables instead: bg-[var(--*)].\n' +
            'Example: bg-blue-600 → bg-[var(--accent-primary)]\n' +
            'See DESIGN_TOKENS.md for the complete mapping.',
        },
        // Text colors
        {
          selector: 'JSXAttribute[name.name="className"] Literal[value=/text-(white|black|gray|slate|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\\d+/]',
          message:
            'Hardcoded text color detected. Use CSS variables instead: text-[var(--*)].\n' +
            'Example: text-gray-900 → text-[var(--text-primary)]\n' +
            'See DESIGN_TOKENS.md for the complete mapping.',
        },
        // Border colors
        {
          selector: 'JSXAttribute[name.name="className"] Literal[value=/border-(white|black|gray|slate|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-\\d+/]',
          message:
            'Hardcoded border color detected. Use CSS variables instead: border-[var(--*)].\n' +
            'Example: border-gray-200 → border-[var(--border-color)]\n' +
            'See DESIGN_TOKENS.md for the complete mapping.',
        },
        // Ring colors
        {
          selector: 'JSXAttribute[name.name="className"] Literal[value=/ring-(blue|red|green|yellow|purple|pink|indigo|gray)-\\d+/]',
          message:
            'Hardcoded ring color detected. Use CSS variables instead: ring-[var(--*)].\n' +
            'Example: ring-blue-500 → ring-[var(--accent-primary)]\n' +
            'See DESIGN_TOKENS.md for the complete mapping.',
        },
        // Gradient from colors
        {
          selector: 'JSXAttribute[name.name="className"] Literal[value=/from-(blue|red|green|yellow|purple|pink|indigo|gray)-\\d+/]',
          message:
            'Hardcoded gradient color detected. Use CSS variable gradients or .gradient-* classes.\n' +
            'Example: Use .gradient-brand class or define gradient in themes.css\n' +
            'See DESIGN_TOKENS.md for available gradient classes.',
        },
        // Gradient to colors
        {
          selector: 'JSXAttribute[name.name="className"] Literal[value=/to-(blue|red|green|yellow|purple|pink|indigo|gray)-\\d+/]',
          message:
            'Hardcoded gradient color detected. Use CSS variable gradients or .gradient-* classes.\n' +
            'Example: Use .gradient-brand class or define gradient in themes.css\n' +
            'See DESIGN_TOKENS.md for available gradient classes.',
        },
        // Template literal background colors
        {
          selector: 'JSXAttribute[name.name="className"] TemplateLiteral > TemplateElement[value.raw=/bg-(white|black|gray|slate|red|blue|green|yellow|purple|pink)-\\d+/]',
          message:
            'Hardcoded background color in template literal detected. Use CSS variables instead.\n' +
            'Example: `bg-${active ? "blue-600" : "gray-200"}` → `bg-[var(${active ? "--accent-primary" : "--bg-secondary"})]`\n' +
            'See DESIGN_TOKENS.md for the complete mapping.',
        },
        // Template literal text colors
        {
          selector: 'JSXAttribute[name.name="className"] TemplateLiteral > TemplateElement[value.raw=/text-(white|black|gray|slate|red|blue|green|yellow|purple|pink)-\\d+/]',
          message:
            'Hardcoded text color in template literal detected. Use CSS variables instead.\n' +
            'See DESIGN_TOKENS.md for the complete mapping.',
        },
        // Template literal border colors
        {
          selector: 'JSXAttribute[name.name="className"] TemplateLiteral > TemplateElement[value.raw=/border-(white|black|gray|slate|red|blue|green|yellow|purple|pink)-\\d+/]',
          message:
            'Hardcoded border color in template literal detected. Use CSS variables instead.\n' +
            'See DESIGN_TOKENS.md for the complete mapping.',
        },
      ],
      */
    },
  },

  // Exception: lib/api.ts is allowed to use invoke()
  {
    files: ['src/lib/api.ts'],
    rules: {
      'no-restricted-imports': 'off', // lib/api.ts needs invoke() to wrap commands
    },
  },

  // Zustand stores are client/UI state only. Backend-owned data belongs in
  // React Query hooks so there is one canonical cache and invalidation path.
  {
    files: ['src/stores/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/lib/api', '**/lib/api', '@/lib/bindings', '**/lib/bindings', '@tauri-apps/**'],
              message: 'Backend access is prohibited in Zustand stores. Use a React Query hook or service.',
            },
          ],
        },
      ],
    },
  },

  // Sidebar surfaces compose query-backed workflows; transport access belongs
  // in workspaceQueries.ts so sibling views share cache invalidation.
  {
    files: ['src/components/Chat/ConversationSidebar.tsx', 'src/components/Chat/sidebar/**/*.tsx'],
    ignores: ['**/__tests__/**', '**/*.test.tsx'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [{
        group: ['@/lib/api', '**/lib/api', '@/lib/bindings', '**/lib/bindings', '@tauri-apps/**'],
        message: 'Use the sidebar query/mutation hooks instead of accessing the backend from a view.',
      }] }],
    },
  },

  // Test files configuration
  {
    files: [
      'src/**/*.test.{ts,tsx}',
      'src/**/*.spec.{ts,tsx}',
      'src/tests/**/*.{ts,tsx}',
    ],
    languageOptions: {
      globals: {
        ...globals.node,
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
        vi: 'readonly',
      },
    },
    rules: {
      // Relax rules for test files
      'no-restricted-syntax': 'off',
      // Test doubles frequently need to stand in for broad framework types.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      'no-console': 'off',
    },
  },

  // Storybook files configuration
  {
    files: ['src/**/*.stories.{ts,tsx}'],
    rules: {
      // Allow hardcoded colors in Storybook
      'no-restricted-syntax': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
    },
  },

  // Configuration files
  {
    files: ['*.config.{js,ts}', 'scripts/**/*.{js,ts}'],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
    rules: {
      '@typescript-eslint/no-var-requires': 'off',
      'no-console': 'off',
    },
  },
];
