import { useRef, useState } from 'react';

import { ArrowRight, Check, ChevronDown, Clock3, Layers3 } from 'lucide-react';

import type { LearningModuleDto, LearningProgramDto } from '@/lib/bindings';

export function CourseSyllabus({ program, moduleId, onSelect, compact = false }: {
  compact?: boolean;
  program: LearningProgramDto;
  moduleId: string;
  onSelect: (module: LearningModuleDto, lessonId: string) => void;
}) {
  const trigger = useRef<HTMLButtonElement>(null);
  const [open, setOpen] = useState(program.summary.status === 'draft');
  const lessons = program.modules.flatMap((module) => module.lessons);
  const minutes = lessons.reduce((total, lesson) => total + lesson.estimatedMinutes, 0);
  const completed = lessons.filter((lesson) => lesson.completed).length;
  return <section className={compact ? "relative min-w-0" : "mt-3 overflow-hidden rounded-2xl border border-border bg-surface"} aria-label="Course syllabus" onKeyDown={(event) => { if (event.key === 'Escape') { setOpen(false); trigger.current?.focus(); } }}>
    <button ref={trigger} type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="course-syllabus-content" className={compact ? "flex min-h-10 items-center gap-2 rounded-lg px-3 text-left hover:bg-surface" : "flex min-h-16 w-full items-center gap-3 px-5 py-3 text-left"}><Layers3 size={19} className="shrink-0 text-accent" /><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-text-primary">Your course journey</span><span className={compact ? "sr-only" : "mt-1 block text-xs leading-5 text-text-muted"}>{program.modules.length} {program.modules.length === 1 ? 'module' : 'modules'} · {lessons.length} {lessons.length === 1 ? 'lesson' : 'lessons'} · about {minutes < 60 ? `${minutes} minutes` : `${Math.round(minutes / 60)} hours`}{program.summary.status === 'active' && ` · ${completed} lessons complete`}</span></span><ChevronDown size={17} className={`shrink-0 text-text-muted transition ${open ? 'rotate-180' : ''}`} /></button>
    <div id="course-syllabus-content" hidden={!open} className={compact ? "absolute right-0 top-full z-30 mt-1 max-h-[75vh] w-[min(960px,calc(100vw-3rem))] overflow-y-auto rounded-2xl border border-border bg-surface p-5 shadow-xl" : "border-t border-border p-4 sm:p-5"}>
      <p className="mb-5 max-w-3xl text-sm leading-6 text-text-secondary">{program.summary.status === 'draft' ? 'Review the whole progression before you begin. Open any lesson below to inspect its objective. Your pace is flexible, and you can revise upcoming work in the Plan.' : 'Follow the sequence or revisit a topic. Opening a lesson never marks it complete.'}</p>
      <ol className="grid gap-4 lg:grid-cols-2">{program.modules.map((module, index) => {
        const done = module.lessons.filter((lesson) => lesson.completed).length;
        return <li key={module.id} className={`min-w-0 rounded-xl border p-4 ${moduleId === module.id ? 'border-accent/40 bg-accent/5' : 'border-border bg-background/40'}`}><div className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-surface font-serif text-lg text-accent">{done === module.lessons.length && done > 0 ? <Check size={16} /> : String(index + 1).padStart(2, '0')}</span><div className="min-w-0"><span className="text-xs font-medium text-accent">Module {index + 1}{index === program.modules.length - 1 && ' · Final module'}</span><h3 className="mt-1 font-serif text-xl leading-snug text-text-primary">{module.title}</h3><p className="mt-2 text-xs leading-5 text-text-secondary">{module.summary}</p></div></div>{Boolean(module.prerequisiteModuleIds?.length) && <p className="mt-3 text-xs text-text-muted">Builds on {module.prerequisiteModuleIds?.map((id) => program.modules.find((m) => m.id === id)?.title).filter(Boolean).join(', ')}</p>}{module.project && <details className="mt-4 rounded-xl border border-accent/20 bg-surface p-3"><summary className="cursor-pointer text-sm font-semibold text-accent">{index === program.modules.length - 1 ? 'Capstone' : 'Project milestone'} · {module.project.title}</summary><p className="mt-3 text-xs leading-5 text-text-secondary">{module.project.brief}</p><h4 className="mt-3 text-xs font-semibold">What you’ll produce</h4><ul className="mt-2 list-disc space-y-1 pl-4 text-xs leading-5 text-text-secondary">{module.project.deliverables.map((d) => <li key={d}>{d}</li>)}</ul><h4 className="mt-3 text-xs font-semibold">What good work looks like</h4><ul className="mt-2 list-disc space-y-1 pl-4 text-xs leading-5 text-text-secondary">{module.project.successCriteria.map((c) => <li key={c}>{c}</li>)}</ul></details>}<ul className="mt-4 space-y-2">{module.outcomes.map((outcome, outcomeIndex) => <li key={`${outcomeIndex}-${outcome}`} className="flex gap-2 text-xs leading-5 text-text-secondary"><Check size={13} className="mt-1 shrink-0 text-accent" />{outcome}</li>)}</ul><ol className="mt-4 divide-y divide-border border-t border-border">{module.lessons.map((lesson, lessonIndex) => <li key={lesson.id}><button type="button" onClick={() => { onSelect(module, lesson.id); if (compact) setOpen(false); }} className="group flex min-h-12 w-full items-center gap-2 py-2 text-left text-sm hover:text-accent"><span className="w-8 shrink-0 text-xs tabular-nums text-text-muted">{lesson.completed ? <Check size={14} className="text-accent" /> : `${index + 1}.${lessonIndex + 1}`}</span><span className="min-w-0 flex-1 text-text-primary">{lesson.title}</span><span className="inline-flex shrink-0 items-center gap-1 text-xs text-text-muted"><Clock3 size={12} />{lesson.estimatedMinutes}m</span><ArrowRight size={13} className="shrink-0 text-accent opacity-0 group-hover:opacity-100 group-focus-visible:opacity-100" /></button></li>)}</ol></li>;
      })}</ol>
    </div>
  </section>;
}
