import { describe, expect, it } from 'vitest';

import { fileRefFromHref, scanFileRefs } from '../extensions/fileRefs';

/** `path:start-end` for a reference with lines, the bare path for one without. */
function refs(text: string, inCode = false): string[] {
  return scanFileRefs(text, () => inCode).map(({ path, lines }) =>
    lines ? `${path}:${lines.startLine}-${lines.endLine}` : path
  );
}

describe('scanFileRefs', () => {
  /** The answer that prompted this: brackets, lists, ranges after commas, paths with no lines. */
  it('reads every reference in a real teaching answer', () => {
    const answer = [
      'The TS side is a generated facade: src/lib/api.ts (hand-written wrapper) + src/lib/bindings.ts, 296 KB of',
      'types generated by npm run bindings:generate [package.json:51; src-tauri/Cargo.toml:35-38]. Commands are',
      'registered per-domain [src-tauri/src/main.rs:9, 64-67]. (e.g., dbResult.ok checked at [src/App.tsx:46-49]).',
      'Errors: dedicated handling (src/lib/errorHandling.ts, ErrorContext) [src/App.tsx:9, 122].',
      'Candle with Metal [src-tauri/Cargo.toml:145-154, 210-213]; see README.md:61-78 and lib.rs:14-59.',
    ].join('\n');
    expect(refs(answer)).toEqual([
      'src/lib/api.ts',
      'src/lib/bindings.ts',
      'package.json:51-51',
      'src-tauri/Cargo.toml:35-38',
      'src-tauri/src/main.rs:9-9',
      'src-tauri/src/main.rs:64-67',
      'src/App.tsx:46-49',
      'src/lib/errorHandling.ts',
      'src/App.tsx:9-9',
      'src/App.tsx:122-122',
      'src-tauri/Cargo.toml:145-154',
      'src-tauri/Cargo.toml:210-213',
      'README.md:61-78',
      'lib.rs:14-59',
    ]);
  });

  it.each([
    ['src/main.rs:12', 'src/main.rs:12-12'],
    ['src/main.rs:10-24', 'src/main.rs:10-24'],
    ['src/main.rs:10–24', 'src/main.rs:10-24'],
    ['src/main.rs:10—24', 'src/main.rs:10-24'],
    ['src/main.rs:24-10', 'src/main.rs:10-24'],
    ['src/main.rs:12:5', 'src/main.rs:12-12'],
    ['src/main.rs:10:1-24:3', 'src/main.rs:10-24'],
    ['src/main.rs#L12', 'src/main.rs:12-12'],
    ['src/main.rs#L10-L24', 'src/main.rs:10-24'],
    ['src/main.rs#L10-24', 'src/main.rs:10-24'],
    ['src/main.rs:L12', 'src/main.rs:12-12'],
    ['src/main.rs:L10-L24', 'src/main.rs:10-24'],
    ['src/main.rs(12)', 'src/main.rs:12-12'],
    ['src/main.rs(12,5)', 'src/main.rs:12-12'],
    ['src/main.rs (lines 10–24)', 'src/main.rs:10-24'],
    ['src/main.rs (line 12)', 'src/main.rs:12-12'],
    ['src/main.rs, line 12', 'src/main.rs:12-12'],
    ['src/main.rs, lines 10 to 24', 'src/main.rs:10-24'],
    ['src/main.rs lines 10-24', 'src/main.rs:10-24'],
    ['src/main.rs at line 12', 'src/main.rs:12-12'],
    ['src/main.rs: lines 3 through 9', 'src/main.rs:3-9'],
    ['src/main.rs L12', 'src/main.rs:12-12'],
    ['src/main.rs L10-L24', 'src/main.rs:10-24'],
    ['src/main.rs — lines 4-6', 'src/main.rs:4-6'],
    ['line 12 of src/main.rs', 'src/main.rs:12-12'],
    ['lines 10–24 in src/main.rs', 'src/main.rs:10-24'],
    ['lines 10-24 of the file `src/main.rs`', 'src/main.rs:10-24'],
    ['**src/main.rs**:12', 'src/main.rs:12-12'],
    ['`src/main.rs`:12', 'src/main.rs:12-12'],
    ['./src/main.rs:3', 'src/main.rs:3-3'],
    ['src\\main.rs:3', 'src/main.rs:3-3'],
    ['/Users/me/proj/src/main.rs:3', '/Users/me/proj/src/main.rs:3-3'],
    ['file:///Users/me/proj/src/main.rs#L3', '/Users/me/proj/src/main.rs:3-3'],
    ['@scope/pkg/index.js:12-4', '@scope/pkg/index.js:4-12'],
    ['src/engine/effect_api.hpp:40', 'src/engine/effect_api.hpp:40-40'],
    ['CMakeLists.txt:7', 'CMakeLists.txt:7-7'],
    ['Makefile:7', 'Makefile:7-7'],
    ['src-tauri/tauri.conf.json:13-28', 'src-tauri/tauri.conf.json:13-28'],
  ])('reads %s', (text, expected) => {
    expect(refs(text)).toEqual([expected]);
  });

  it.each([
    ['[a.rs:1; b.rs:2-3]', ['a.rs:1-1', 'b.rs:2-3']],
    ['(src/a.rs:1, src/b.rs:2)', ['src/a.rs:1-1', 'src/b.rs:2-2']],
    ['src/a.rs lines 3 and 5', ['src/a.rs:3-3', 'src/a.rs:5-5']],
    ['src/a.rs:3, 5 and 9-11.', ['src/a.rs:3-3', 'src/a.rs:5-5', 'src/a.rs:9-11']],
    ['src/a.rs#L3, L8-L9', ['src/a.rs:3-3', 'src/a.rs:8-9']],
    ['See src/a.rs:12, 2024 was a good year', ['src/a.rs:12-12']],
    ['src/a.rs:9, 64-67 handle the exit', ['src/a.rs:9-9', 'src/a.rs:64-67']],
  ])('reads the list %s', (text, expected) => {
    expect(refs(text)).toEqual(expected);
  });

  it('keeps a closing period, comma or bracket out of the path', () => {
    expect(refs('Open src/lib/api.ts.')).toEqual(['src/lib/api.ts']);
    expect(refs('Read (src/lib/api.ts), then go on.')).toEqual(['src/lib/api.ts']);
    expect(refs('End at src/a.rs:12.')).toEqual(['src/a.rs:12-12']);
  });

  it('names bare files only where they are plainly files', () => {
    expect(refs('Edit package.json and Cargo.toml')).toEqual(['package.json', 'Cargo.toml']);
    expect(refs('main.rs', true)).toEqual(['main.rs']);
    expect(refs('.gitignore', true)).toEqual(['.gitignore']);
    expect(refs('Built with Node.js and Vue.js')).toEqual([]);
    expect(refs('App.js', true)).toEqual(['App.js']);
  });

  it.each([
    'Meet at 10:30 for a 16:9 screen',
    'localhost:5173 and 127.0.0.1:56241',
    'https://example.com:443/docs/page.html',
    'https://github.com/org/repo/blob/main/src/main.rs#L12',
    'github.com/org/repo/main.rs',
    'example.com:443',
    'version v1.2.3 and 2.0.1',
    'e.g. this, i.e. that, etc.',
    'npm run bindings:generate -- --check',
    'tauri::Builder::default()',
    'and/or, TCP/IP, km/h, n/a',
    '@tauri-apps/api/event',
    'src-tauri/src/features/',
    'Result<T, E> and Option<T>',
    'step 3: run it',
  ])('leaves %s as text', (text) => {
    expect(refs(text)).toEqual([]);
  });

  it.each(['dbResult.ok', 'self.status', 'app.manage(state)', 'foo:12', 'let x = a.b:3'])(
    'leaves %s as code',
    (text) => {
      expect(refs(text, true)).toEqual([]);
    }
  );

  it('marks where each reference sits, so a chip covers exactly it', () => {
    const text = 'See [src/a.rs:9, 64-67] and lines 3–4 of lib.rs.';
    const spans = scanFileRefs(text).map(({ start, end }) => text.slice(start, end));
    expect(spans).toEqual(['src/a.rs:9', '64-67', 'lines 3–4 of lib.rs']);
  });
});

describe('fileRefFromHref', () => {
  it.each([
    ['src/main.rs#L12', 'src/main.rs', 12],
    ['src-tauri/src/main.rs:64-67', 'src-tauri/src/main.rs', 64],
    ['./lib/util.ts', 'lib/util.ts', null],
    ['file:///Users/me/proj/a.rs#L3', '/Users/me/proj/a.rs', 3],
    ['src/my%20file.rs#L2', null, null],
  ])('reads the link address %s', (href, path, line) => {
    const ref = fileRefFromHref(href);
    expect(ref?.path ?? null).toBe(path);
    expect(ref?.lines?.startLine ?? null).toBe(path ? line : null);
  });

  it.each(['https://example.com/a.rs', 'mailto:me@example.com', 'http://localhost:5173/src/a.rs', '#section'])(
    'leaves a link to %s alone',
    (href) => {
      expect(fileRefFromHref(href)).toBeNull();
    }
  );
});
