//! The bundled CPython runtime: where it is installed and whether it is intact.
//!
//! The runtime bundle is generated by `scripts/build-learning-python.sh` from
//! a pinned upstream CPython release and WASI SDK. It is verified here, in the
//! app; learner programs run on it only inside the lab runner's child process.

use crate::features::learning::lab_runtime::{LearningLabExecutionResult, LearningLabRunStatus};
use crate::shared::error::{AppError, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

pub(super) const WASM_NAME: &str = "python.wasm";
const STDLIB_NAME: &str = "python314.zip";
const STDLIB_RELATIVE_PATH: &str = "lib/python314.zip";
const MANIFEST_NAME: &str = "runtime-manifest.json";

static RUNTIME_ROOT: OnceLock<PathBuf> = OnceLock::new();
static BUNDLE_VALID: OnceLock<bool> = OnceLock::new();

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct RuntimeManifest {
    python_version: String,
    wasm_sha256: String,
    stdlib_sha256: String,
}

/// What a lab run needs to start the interpreter: the verified bundle, and
/// where the compiled interpreter may be kept between runs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PythonBundle {
    pub root: PathBuf,
    pub module_cache: Option<PathBuf>,
}

/// Configure the bundled runtime directory. The directory contains
/// `python.wasm`, `lib/python314.zip`, and the build-generated digest manifest.
pub fn configure_python_runtime(resource_root: PathBuf) -> Result<()> {
    if let Some(existing) = RUNTIME_ROOT.get() {
        if existing == &resource_root {
            return Ok(());
        }
        return Err(AppError::InvalidConfig(
            "The Python runtime was already configured from a different resource path.".into(),
        ));
    }
    verify_runtime_bundle(&resource_root).map_err(|error| {
        AppError::InvalidConfig(format!("The bundled Python runtime is invalid: {error}"))
    })?;
    let _ = BUNDLE_VALID.set(true);
    RUNTIME_ROOT
        .set(resource_root)
        .map_err(|_| AppError::InvalidConfig("The Python runtime could not be configured.".into()))
}

/// Whether a complete, digest-verified CPython WASI bundle is available.
pub fn python_runtime_available() -> bool {
    if let Some(available) = BUNDLE_VALID.get() {
        return *available;
    }
    runtime_root().is_some_and(|root| {
        let available = verify_runtime_bundle(&root).is_ok();
        let _ = BUNDLE_VALID.set(available);
        available
    })
}

/// The verified bundle, when one is configured and intact.
pub(super) fn bundle() -> Option<PythonBundle> {
    let root = runtime_root()?;
    python_runtime_available().then(|| PythonBundle {
        root,
        module_cache: module_cache_dir(),
    })
}

#[cfg(not(test))]
fn module_cache_dir() -> Option<PathBuf> {
    dirs::cache_dir().map(|directory| directory.join("lattice").join("learning-python"))
}

#[cfg(test)]
fn module_cache_dir() -> Option<PathBuf> {
    Some(std::env::temp_dir().join("lattice-learning-python-test-modules"))
}

#[cfg(all(test, feature = "learning-labs"))]
pub(super) fn test_bundle() -> PythonBundle {
    PythonBundle {
        root: runtime_root().unwrap_or_default(),
        module_cache: module_cache_dir(),
    }
}

/// The interpreter's SHA-256 as the bundle's manifest records it.
#[cfg(feature = "learning-labs")]
pub(super) fn wasm_digest(root: &Path) -> std::result::Result<String, String> {
    Ok(read_manifest(root)?.wasm_sha256)
}

fn read_manifest(root: &Path) -> std::result::Result<RuntimeManifest, String> {
    let manifest_bytes = fs::read(root.join(MANIFEST_NAME))
        .map_err(|error| format!("Python runtime manifest is missing: {error}"))?;
    serde_json::from_slice(&manifest_bytes)
        .map_err(|error| format!("Python runtime manifest is invalid: {error}"))
}

pub(super) fn unavailable_result() -> LearningLabExecutionResult {
    LearningLabExecutionResult {
        status: LearningLabRunStatus::RuntimeUnavailable,
        exit_code: None,
        stdout: String::new(),
        stderr: "The bundled Python runtime is missing or failed its integrity check.".into(),
        output_truncated: false,
        duration_ms: 0,
    }
}

fn runtime_root() -> Option<PathBuf> {
    RUNTIME_ROOT.get().cloned().or({
        #[cfg(test)]
        {
            Some(PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("resources/learning-python"))
        }
        #[cfg(not(test))]
        {
            None
        }
    })
}

fn verify_runtime_bundle(root: &Path) -> std::result::Result<(), String> {
    let wasm_path = root.join(WASM_NAME);
    let stdlib_path = root.join(STDLIB_RELATIVE_PATH);
    let manifest = read_manifest(root)?;
    if manifest.python_version != "3.14.8" {
        return Err("The bundled CPython version does not match this application.".into());
    }
    verify_digest(&wasm_path, &manifest.wasm_sha256, WASM_NAME)?;
    verify_digest(&stdlib_path, &manifest.stdlib_sha256, STDLIB_NAME)?;
    Ok(())
}

fn verify_digest(path: &Path, expected: &str, label: &str) -> std::result::Result<(), String> {
    let bytes = fs::read(path).map_err(|error| format!("Python {label} is missing: {error}"))?;
    let digest = Sha256::digest(bytes);
    if hex::encode(digest) != expected {
        return Err(format!(
            "The bundled Python {label} failed its SHA-256 check."
        ));
    }
    Ok(())
}
