// This file was auto-generated by Specta. DO NOT EDIT MANUALLY.
// Generated by: src/crates/recall/ipc/bindings.rs
// Regenerate: cargo test ipc::bindings::generate_ts_bindings

// This file has been generated by Specta. DO NOT EDIT.

/**
 * Structured error information for API responses.
 * 
 * Contains an error code for programmatic handling, a human-readable message,
 * and optional details for debugging.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::shared::api_result::{ApiError, ErrorCode};
 * let error = ApiError {
 * code: ErrorCode::NotFound,
 * message: "Document not found".to_string(),
 * details: Some("ID: doc-123".to_string()),
 * };
 * ```
 */
export type ApiError = { 
/**
 * Error code for programmatic handling
 */
code: ErrorCode; 
/**
 * Human-readable error message
 */
message: string; 
/**
 * Optional additional details (sanitized for security)
 */
details?: string | null }

/**
 * API result wrapper for IPC gateway responses.
 * 
 * This type wraps all gateway responses in a consistent format that discriminates
 * between success and error cases. It uses an untagged enum for clean JSON serialization.
 * 
 * # JSON Serialization
 * 
 * - Success: `{ "ok": true, "data": <T> }`
 * - Error: `{ "ok": false, "error": { "code": "...", "message": "...", "details"?: "..." } }`
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::shared::api_result::{ApiResult, ErrorCode};
 * let success = ApiResult::success("hello");
 * assert!(success.is_ok());
 * 
 * let error = ApiResult::<String>::error(ErrorCode::NotFound, "Not found");
 * assert!(!error.is_ok());
 * ```
 */
export type ApiResult<T> = 
/**
 * Success variant containing data
 */
{ 
/**
 * Always true for success
 */
ok: boolean; 
/**
 * The successful result data
 */
data: T } | 
/**
 * Error variant containing error information
 */
{ 
/**
 * Always false for errors
 */
ok: boolean; 
/**
 * Structured error information
 */
error: ApiError }

export type BindingsRegistry = { error_code: ErrorCode; api_error: ApiError; string_result: ApiResult<string> }

/**
 * Comprehensive error code enumeration for API responses.
 * 
 * These codes allow the frontend to handle errors programmatically without
 * parsing error messages. Each code maps to a specific error category.
 * 
 * # Serialization
 * 
 * Error codes serialize to SCREAMING_SNAKE_CASE for consistency with typical
 * API conventions.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::shared::api_result::ErrorCode;
 * let code = ErrorCode::NotFound;
 * let json = serde_json::to_string(&code).unwrap();
 * assert_eq!(json, "\"NOT_FOUND\"");
 * ```
 */
export type ErrorCode = 
/**
 * Requested resource was not found
 */
"NOT_FOUND" | 
/**
 * Resource already exists
 */
"ALREADY_EXISTS" | 
/**
 * Resource has been deleted or is no longer available
 */
"GONE" | 
/**
 * Operation not permitted
 */
"PERMISSION_DENIED" | 
/**
 * Invalid credentials or authentication failure
 */
"UNAUTHORIZED" | 
/**
 * Security violation detected
 */
"SECURITY_VIOLATION" | 
/**
 * Input validation failed
 */
"VALIDATION_ERROR" | 
/**
 * Invalid input format
 */
"INVALID_INPUT" | 
/**
 * Invalid configuration
 */
"INVALID_CONFIG" | 
/**
 * Invalid state for requested operation
 */
"INVALID_STATE" | 
/**
 * Constraint violation
 */
"CONSTRAINT_VIOLATION" | 
/**
 * File not found
 */
"FILE_NOT_FOUND" | 
/**
 * File is too large to process
 */
"FILE_TOO_LARGE" | 
/**
 * File type not supported
 */
"UNSUPPORTED_FILE_TYPE" | 
/**
 * File system operation failed
 */
"FILE_SYSTEM_ERROR" | 
/**
 * File read error
 */
"FILE_READ_ERROR" | 
/**
 * File write error
 */
"FILE_WRITE_ERROR" | 
/**
 * Database operation failed
 */
"DATABASE_ERROR" | 
/**
 * Database connection failed
 */
"DATABASE_CONNECTION_ERROR" | 
/**
 * Database migration failed
 */
"MIGRATION_ERROR" | 
/**
 * Network operation failed
 */
"NETWORK_ERROR" | 
/**
 * Request timeout
 */
"TIMEOUT" | 
/**
 * Rate limit exceeded
 */
"RATE_LIMIT_EXCEEDED" | 
/**
 * Required service is not available
 */
"SERVICE_NOT_AVAILABLE" | 
/**
 * Service initialization failed
 */
"SERVICE_INITIALIZATION_ERROR" | 
/**
 * AI model not loaded or unavailable
 */
"MODEL_NOT_LOADED" | 
/**
 * AI model loading failed
 */
"MODEL_LOAD_ERROR" | 
/**
 * Data processing failed
 */
"PROCESSING_ERROR" | 
/**
 * Serialization failed
 */
"SERIALIZATION_ERROR" | 
/**
 * Deserialization failed
 */
"DESERIALIZATION_ERROR" | 
/**
 * Parsing error
 */
"PARSING_ERROR" | 
/**
 * Embedding generation failed
 */
"EMBEDDING_ERROR" | 
/**
 * Content extraction failed
 */
"EXTRACTION_ERROR" | 
/**
 * Tokenization error
 */
"TOKENIZATION_ERROR" | 
/**
 * Concurrent modification detected
 */
"CONCURRENT_MODIFICATION" | 
/**
 * Processing queue is full
 */
"QUEUE_FULL" | 
/**
 * Backup creation failed
 */
"BACKUP_CREATION_FAILED" | 
/**
 * Backup restore failed
 */
"BACKUP_RESTORE_FAILED" | 
/**
 * Backup file is corrupted
 */
"BACKUP_CORRUPTED" | 
/**
 * Internal server error
 */
"INTERNAL_ERROR" | 
/**
 * Feature not implemented
 */
"NOT_IMPLEMENTED" | 
/**
 * Generic error
 */
"UNKNOWN"


