/**
 * Error Code Constants
 *
 * SYNCHRONIZED WITH RUST BACKEND (api_result.rs)
 * Matches all 42 error codes from Rust ErrorCode enum exactly.
 * Provides type-safe error code constants for frontend error handling.
 */

export const ErrorCode = {
  // Resource Errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  GONE: 'GONE',

  // Permission & Security Errors
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  SECURITY_VIOLATION: 'SECURITY_VIOLATION',

  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_CONFIG: 'INVALID_CONFIG',
  INVALID_STATE: 'INVALID_STATE',
  CONSTRAINT_VIOLATION: 'CONSTRAINT_VIOLATION',

  // File System Errors
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  FILE_SYSTEM_ERROR: 'FILE_SYSTEM_ERROR',
  FILE_READ_ERROR: 'FILE_READ_ERROR',
  FILE_WRITE_ERROR: 'FILE_WRITE_ERROR',

  // Database Errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  MIGRATION_ERROR: 'MIGRATION_ERROR',

  // Network Errors
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Service Errors
  SERVICE_NOT_AVAILABLE: 'SERVICE_NOT_AVAILABLE',
  SERVICE_INITIALIZATION_ERROR: 'SERVICE_INITIALIZATION_ERROR',
  MODEL_NOT_LOADED: 'MODEL_NOT_LOADED',
  MODEL_LOAD_ERROR: 'MODEL_LOAD_ERROR',

  // Processing Errors
  PROCESSING_ERROR: 'PROCESSING_ERROR',
  SERIALIZATION_ERROR: 'SERIALIZATION_ERROR',
  DESERIALIZATION_ERROR: 'DESERIALIZATION_ERROR',
  PARSING_ERROR: 'PARSING_ERROR',
  EMBEDDING_ERROR: 'EMBEDDING_ERROR',
  EXTRACTION_ERROR: 'EXTRACTION_ERROR',
  TOKENIZATION_ERROR: 'TOKENIZATION_ERROR',

  // Concurrency Errors
  CONCURRENT_MODIFICATION: 'CONCURRENT_MODIFICATION',
  QUEUE_FULL: 'QUEUE_FULL',

  // Backup & Recovery Errors
  BACKUP_CREATION_FAILED: 'BACKUP_CREATION_FAILED',
  BACKUP_RESTORE_FAILED: 'BACKUP_RESTORE_FAILED',
  BACKUP_CORRUPTED: 'BACKUP_CORRUPTED',

  // Generic Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  UNKNOWN: 'UNKNOWN',
} as const;

/**
 * Type extracted from error code constants
 */
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];
