// Auto-generated TypeScript bindings for Diamond Standard Plugins
// DO NOT EDIT - This file is auto-generated by export_bindings.rs
// To regenerate: cargo run --bin export_bindings
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Download a model by ID
 * 
 * Thin wrapper that delegates to the existing download_model implementation in llm.rs.
 * Maps the response from DownloadModelResponseDto to DownloadModelResponse.
 */
async downloadModel(modelId: string) : Promise<Result<DownloadModelResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel an in-progress download
 */
async cancelDownload(downloadId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { downloadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a downloaded model
 */
async deleteModel(modelId: string, deleteFile: boolean) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId, deleteFile }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all downloaded models
 */
async listDownloadedModels() : Promise<Result<DownloadedModelResponse[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_downloaded_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get download status for a specific download
 */
async getDownloadStatus(downloadId: string) : Promise<Result<DownloadStatus, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_download_status", { downloadId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set active embedding model
 */
async setActiveEmbeddingModel(modelId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_embedding_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set active inference model (chat model)
 */
async setActiveInferenceModel(modelId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_inference_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the active utility model (used for HyDE, routing, intent classification).
 */
async setActiveUtilityModel(modelId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_utility_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear the active utility model — reverts to using the chat model for HyDE/routing.
 */
async clearActiveUtilityModel() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_active_utility_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get active models (both chat and embedding)
 */
async getActiveModels() : Promise<Result<ActiveModels, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_active_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate model compatibility with system
 */
async validateModelCompatibility(modelId: string) : Promise<Result<CompatibilityReport, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_model_compatibility", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get model information by ID
 */
async getModelInfo(modelId: string) : Promise<Result<DownloadedModelResponse | null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export model metadata to file
 */
async exportModel(modelId: string, exportPath: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_model", { modelId, exportPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import model from file
 */
async importModel(importPath: string) : Promise<Result<DownloadedModelResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_model", { importPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh model cache (invalidates LLM and embedding caches)
 */
async refreshModelCache() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_model_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Detect system hardware capabilities.
 * 
 * Returns comprehensive system information:
 * - RAM (total, available)
 * - CPU (cores, model)
 * - GPU (type, acceleration, VRAM)
 * - Disk (available space)
 * 
 * # Example
 * 
 * ```typescript
 * const capabilities = await invoke('detect_system_capabilities');
 * console.log(`RAM: ${capabilities.total_ram_gb} GB`);
 * console.log(`GPU: ${capabilities.gpu_type}`);
 * ```
 */
async detectSystemCapabilities() : Promise<Result<SystemCapabilitiesResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_system_capabilities") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get compatible models for a specific category.
 * 
 * Returns models ranked by compatibility score, with detailed
 * compatibility analysis for each model.
 * 
 * # Arguments
 * - `category` - "LLM", "Embedding", or "OCR"
 * 
 * # Returns
 * List of model recommendations sorted by ranking score (best first).
 * 
 * # Example
 * 
 * ```typescript
 * const models = await invoke('get_compatible_models', {
 * category: 'LLM'
 * });
 * 
 * for (const model of models) {
 * console.log(`${model.model.name}: ${model.compatibility.compatibility_level}`);
 * console.log(`Score: ${model.ranking_score}/100`);
 * }
 * ```
 */
async getCompatibleModels(category: string) : Promise<Result<ModelRecommendationDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_compatible_models", { category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get all recommended models across all categories.
 * 
 * Returns models ranked by compatibility, grouped by category.
 * 
 * # Example
 * 
 * ```typescript
 * const allModels = await invoke('get_all_recommended_models');
 * console.log(`Total compatible models: ${allModels.length}`);
 * ```
 */
async getAllRecommendedModels() : Promise<Result<ModelRecommendationDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_recommended_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search external model catalogs (Hugging Face).
 * 
 * Uses Hugging Face as the source of truth for downloadable models,
 * ranks them by relevance, and returns unified results.
 * 
 * # Features
 * - Searches Hugging Face (cached)
 * - Filters by category, size, capabilities
 * - Ranks by relevance score (0-100)
 * - Caches results for 1 hour (TTL)
 * - Graceful degradation on API errors
 * 
 * # Example
 * 
 * ```typescript
 * const results = await invoke('search_model_catalog', {
 * query: 'llama chat',
 * category: 'LLM',
 * max_size_gb: 5.0,
 * required_capabilities: ['chat', 'code'],
 * limit: 10
 * });
 * 
 * for (const result of results) {
 * console.log(`${result.model.name}: ${result.relevance_score}/100`);
 * console.log(`Source: ${result.source}`);
 * }
 * ```
 */
async searchModelCatalog(request: SearchModelCatalogRequest) : Promise<Result<ModelSearchResultDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_model_catalog", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Refresh model catalog cache.
 * 
 * Clears the catalog cache to force fresh API calls on next search.
 * 
 * # Example
 * 
 * ```typescript
 * await invoke('refresh_model_catalog');
 * console.log('Catalog cache refreshed');
 * ```
 */
async refreshModelCatalog() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_model_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear model catalog cache.
 * 
 * Removes all cached catalog entries, forcing fresh API calls.
 * 
 * # Example
 * 
 * ```typescript
 * const deleted = await invoke('clear_model_catalog_cache');
 * console.log(`Cleared ${deleted} cache entries`);
 * ```
 */
async clearModelCatalogCache() : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_model_catalog_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get model catalog cache statistics.
 * 
 * Returns metrics about cache usage and effectiveness.
 * 
 * # Example
 * 
 * ```typescript
 * const stats = await invoke('get_model_catalog_stats');
 * console.log(`Total: ${stats.total_entries}`);
 * console.log(`Valid: ${stats.valid_entries}`);
 * console.log(`Expired: ${stats.expired_entries}`);
 * ```
 */
async getModelCatalogStats() : Promise<Result<ModelCatalogStats, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_catalog_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Finds documents similar to a given chunk
 * 
 * Retrieves documents semantically similar to the specified chunk by using the chunk's
 * content as the search query. Automatically filters out the source chunk from results
 * to avoid self-matches. Useful for "more like this" features.
 * 
 * # Arguments
 * 
 * * `container` - Service container with search and enrichment services
 * * `chunk_id` - ID of the chunk to find similar documents for
 * * `limit` - Maximum number of similar documents to return (default: 10)
 * 
 * # Returns
 * 
 * * `Ok(Vec<SearchResultDto>)` - Similar documents ranked by semantic similarity
 * * `Err(AppError)` - If rate limited, chunk not found, or search fails
 * 
 * # Errors
 * 
 * * `AppError::RateLimitExceeded` - Too many search requests (rate limited)
 * * `AppError::NotFound` - Chunk ID not found in database
 * * `AppError::Other` - Embedding or search execution failed
 * 
 * # Example
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * 
 * // Find similar documents to a chunk
 * const similar = await invoke('find_similar', {
 * chunkId: 'chunk_abc123',
 * limit: 10
 * });
 * 
 * console.log(`Found ${similar.length} similar documents`);
 * similar.forEach(doc => {
 * console.log(`${doc.title}: ${doc.score}`);
 * });
 * ```
 * 
 * # Security
 * 
 * - **Rate Limiting (CWE-770)**: Prevents DoS attacks
 * - **Audit Logging (CWE-778)**: Logs similarity searches with chunk ID
 * 
 * # Algorithm
 * 
 * 1. Retrieve source chunk content from database
 * 2. Generate embedding for chunk content
 * 3. Perform vector similarity search
 * 4. Filter out source chunk from results (prevent self-match)
 * 5. Take top N results after filtering
 * 6. Enrich with metadata
 * 
 * # Use Cases
 * 
 * - "More like this" document recommendations
 * - Related content suggestions
 * - Document clustering visualization
 * - Duplicate detection
 * 
 * # Command Flow
 * 
 * 1. Rate limiting check
 * 2. Fetch chunk content using enrichment service
 * 3. Error if chunk not found
 * 4. Embed chunk content
 * 5. Vector similarity search (limit + 1 to account for self-match)
 * 6. Filter out source chunk
 * 7. Take top `limit` results
 * 8. Enrich with metadata
 * 9. Log audit event with "similar:{chunk_id}" query
 * 10. Return similar documents
 */
async findSimilar(chunkId: string, limit: number | null) : Promise<Result<SearchResultDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_similar", { chunkId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Time-aware search with recency boosting
 * 
 * Performs hybrid search with automatic boosting of recent documents. Combines semantic
 * similarity with temporal decay to surface fresh content while maintaining relevance.
 * Configurable recency weight and maximum age filter.
 * 
 * # Arguments
 * 
 * * `container` - Service container with hybrid search service
 * * `options` - Search options including query, recency weight, and age filter
 * 
 * # Returns
 * 
 * * `Ok(Vec<SearchResultDto>)` - Search results ranked with recency boost
 * * `Err(AppError)` - If rate limited, validation fails, or execution fails
 * 
 * # Errors
 * 
 * * `AppError::RateLimitExceeded` - Too many search requests (rate limited)
 * * `AppError::InvalidInput` - Query validation failed, invalid recency weight, or negative max_age_days
 * * `AppError::Other` - Embedding or search execution failed
 * 
 * # Example
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * 
 * interface RecencySearchOptions {
 * query: string;
 * limit?: number;
 * recencyWeight?: number;  // 0.0 to 1.0
 * maxAgeDays?: number;     // positive integer
 * }
 * 
 * // Search with recency boost (favor recent documents)
 * const results = await invoke('search_with_recency', {
 * options: {
 * query: 'project status',
 * limit: 15,
 * recencyWeight: 0.3,  // 30% weight to recency
 * maxAgeDays: 90       // Only last 3 months
 * }
 * });
 * 
 * console.log('Recent relevant documents:');
 * results.forEach(doc => {
 * console.log(`${doc.title} (score: ${doc.score})`);
 * });
 * ```
 * 
 * # Security
 * 
 * - **Rate Limiting (CWE-770)**: Prevents DoS attacks
 * - **Input Validation**: Sanitizes query, validates recency_weight ∈ [0, 1], validates max_age_days > 0
 * - **Audit Logging (CWE-778)**: Logs searches with result count
 * 
 * # Recency Scoring
 * 
 * **Formula**: `final_score = (1 - recency_weight) * relevance_score + recency_weight * recency_score`
 * 
 * - **recency_weight**: 0.0 = pure relevance, 1.0 = pure recency
 * - **recency_score**: Exponential decay based on document age
 * - **max_age_days**: Hard filter - documents older than this are excluded
 * 
 * **Default Values**:
 * - `limit`: 10
 * - `recency_weight`: 0.1 (10% recency, 90% relevance)
 * - `max_age_days`: 730 (2 years)
 * 
 * # Validation
 * 
 * - `recency_weight` must be in range [0.0, 1.0]
 * - `max_age_days` must be positive (> 0)
 * - Empty validation errors return `AppError::InvalidInput`
 * 
 * # Use Cases
 * 
 * - Finding recent project updates
 * - News/blog search favoring fresh content
 * - Status report queries
 * - Time-sensitive document retrieval
 * 
 * # Command Flow
 * 
 * 1. Rate limiting check
 * 2. Input validation (query, recency_weight, max_age_days)
 * 3. Apply defaults (limit=10, recency_weight=0.1, max_age_days=730)
 * 4. Validate recency_weight ∈ [0, 1]
 * 5. Validate max_age_days > 0
 * 6. Embed query
 * 7. Execute recency-aware hybrid search
 * 8. Enrich results with metadata
 * 9. Log audit event
 * 10. Return time-boosted results
 */
async searchWithRecency(options: RecencySearchOptions) : Promise<Result<SearchResultDto[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_with_recency", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Batch search command for processing multiple queries in parallel
 * 
 * ## Overview
 * 
 * Processes multiple search queries efficiently in a single operation,
 * returning results for each query in the same order as provided.
 * 
 * ## Arguments
 * 
 * * `container` - DI container with services
 * * `queries` - List of search queries to process
 * * `limit` - Maximum results per query (default: 10)
 * * `search_mode` - Search algorithm to use (Vector, Keyword, Hybrid)
 * 
 * ## Returns
 * 
 * Vector of result vectors, one for each query in input order.
 * 
 * ## Security
 * 
 * - Rate limiting applied once for the batch
 * - Each query validated individually
 * - Audit logged as batch operation
 * 
 * ## Example
 * 
 * ```javascript
 * const results = await VaultAPI.batchSearch(
 * ['query1', 'query2', 'query3'],
 * 10,
 * 'hybrid'
 * );
 * // results[0] = results for 'query1'
 * // results[1] = results for 'query2'
 * // results[2] = results for 'query3'
 * ```
 */
async batchSearch(queries: string[], limit: number | null, searchMode: string | null) : Promise<Result<SearchResultDto[][], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_search", { queries, limit, searchMode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async indexFile(path: string, spaceId: string | null) : Promise<Result<IndexFileResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("index_file", { path, spaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async indexDirectory(path: string, recursive: boolean, spaceId: string | null) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("index_directory", { path, recursive, spaceId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Legacy Tauri shim - Retrieves file metadata (size and modification time) for a given path
 * 
 * # Arguments
 * 
 * * `path` - The absolute path to the file
 * * `container` - Service container with security context
 * 
 * # Example
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * 
 * const metadata = await invoke<FileMetadata>('get_file_metadata', {
 * path: '/Users/josh/Documents/report.pdf'
 * });
 * ```
 */
async getFileMetadata(path: string) : Promise<Result<FileMetadataDto, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_metadata", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileContent(path: string) : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_content", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateFileMetadata(path: string, metadata: MetadataUpdate) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_file_metadata", { path, metadata }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteFileIndex(path: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_file_index", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listIndexedFiles(limit: number | null) : Promise<Result<string[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_indexed_files", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getIndexingStatus() : Promise<Result<IndexingStatus, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_indexing_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pauseIndexing() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_indexing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resumeIndexing() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_indexing") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reindexFile(path: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reindex_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateFilePath(path: string) : Promise<Result<boolean, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_file_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConfig() : Promise<Result<AppConfig, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_config") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveConfig(config: AppConfig) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWatchFolders() : Promise<Result<string[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_watch_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addWatchFolder(path: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_watch_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeWatchFolder(path: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_watch_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async credentialsStore(service: string, key: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("credentials_store", { service, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async credentialsGet(service: string) : Promise<Result<string | null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("credentials_get", { service }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async credentialsDelete(service: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("credentials_delete", { service }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async credentialsHas(service: string) : Promise<Result<boolean, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("credentials_has", { service }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async credentialsClearAll() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("credentials_clear_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async credentialsSetEndpoint(endpoint: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("credentials_set_endpoint", { endpoint }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async credentialsGetEndpoint() : Promise<Result<string | null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("credentials_get_endpoint") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async healthCheck() : Promise<Result<HealthStatus, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSystemStats() : Promise<Result<SystemStats, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_system_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVersion() : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_version") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async initializeDatabase() : Promise<Result<string, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_database") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAllTagsWithCounts() : Promise<Result<TagWithCountDto[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all_tags_with_counts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDocumentTags(documentId: string) : Promise<Result<TagDto[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_document_tags", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyTags(request: ApplyTagsRequestDto) : Promise<Result<TagDto[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_tags", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeTagFromDocument(request: RemoveTagRequestDto) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_tag_from_document", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateTagsForDocument(request: GenerateTagsRequestDto) : Promise<Result<string[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_tags_for_document", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addFavorite(documentId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_favorite", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeFavorite(documentId: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_favorite", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFavorites() : Promise<Result<FavoriteDocument[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_favorites") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isFavorite(documentId: string) : Promise<Result<boolean, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_favorite", { documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Convenience wrapper for clear_search_cache with shorter name
 * 
 * Provides backward compatibility for frontend code using the generic `clear_cache` name.
 * Delegates to `clear_search_cache` which clears the search query cache.
 * 
 * # Returns
 * 
 * * `Ok(())` - Cache cleared successfully
 * * `Err(AppError)` - Cache clear failed (rare)
 * 
 * # Example
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * 
 * // Clear cache using short name
 * await invoke('clear_cache');
 * ```
 * 
 * # Note
 * 
 * This is a convenience alias for `clear_search_cache`. Both commands perform
 * the same operation. Use whichever name is more convenient for your use case.
 */
async clearCache() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns detailed cache statistics including size and performance metrics
 * 
 * Provides comprehensive statistics about the search cache including current size,
 * capacity, hit/miss counts, time saved, and calculated hit rate. Useful for
 * monitoring cache effectiveness and tuning cache size.
 * 
 * # Returns
 * 
 * * `Ok(CacheStats)` - Detailed cache statistics
 * * `Err(AppError)` - Stats retrieval failed (rare)
 * 
 * # Example
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * 
 * interface CacheStats {
 * size: number;              // Current entries (e.g., 42)
 * capacity: number;          // Max entries (e.g., 100)
 * hits: number;              // Cache hits (e.g., 127)
 * misses: number;            // Cache misses (e.g., 85)
 * totalTimeSavedMs: number;  // Time saved by cache hits (e.g., 6350ms)
 * hitRate: number;           // Hit rate 0.0-1.0 (e.g., 0.599 = 59.9%)
 * }
 * 
 * // Get cache stats
 * const stats = await invoke<CacheStats>('get_cache_stats');
 * 
 * console.log(`Cache: ${stats.size}/${stats.capacity} entries`);
 * console.log(`Hit rate: ${(stats.hitRate * 100).toFixed(1)}%`);
 * console.log(`Time saved: ${(stats.totalTimeSavedMs / 1000).toFixed(1)}s`);
 * 
 * // Display in UI
 * updateCacheDisplay({
 * usage: `${stats.size} / ${stats.capacity}`,
 * hitRate: `${(stats.hitRate * 100).toFixed(1)}%`,
 * timeSaved: `${(stats.totalTimeSavedMs / 1000).toFixed(1)}s`
 * });
 * 
 * // Monitor cache effectiveness
 * if (stats.hitRate < 0.3) {
 * console.warn('Low cache hit rate. Consider increasing capacity.');
 * }
 * ```
 * 
 * # Statistics Breakdown
 * 
 * - **size**: Current number of cached entries
 * - **capacity**: Maximum entries before LRU eviction
 * - **hits**: Number of cache hits since startup
 * - **misses**: Number of cache misses since startup
 * - **total_time_saved_ms**: Estimated time saved by cache hits
 * - **hit_rate**: hits / (hits + misses), 0.0 to 1.0
 * 
 * # Use Cases
 * 
 * - **Dashboard**: Display cache performance in admin UI
 * - **Monitoring**: Track cache effectiveness over time
 * - **Tuning**: Determine optimal cache capacity
 * - **Diagnostics**: Troubleshoot search performance issues
 * 
 * # Performance
 * 
 * - **Access Time**: ~1μs (atomic counter reads)
 * - **No Locking**: Lock-free atomic operations
 * - **Synchronous**: Instant return
 * 
 * # Architecture
 * 
 * Direct accessor to global QUERY_CACHE singleton statistics
 */
async getCacheStats() : Promise<Result<SearchCacheStats, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_stats") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns cache performance metrics (subset of stats)
 * 
 * Provides focused performance metrics without size/capacity information. Lighter
 * weight than `get_cache_stats` for frequent polling or metric collection.
 * 
 * # Returns
 * 
 * * `Ok(CacheMetrics)` - Performance metrics (hits, misses, time saved, hit rate)
 * * `Err(AppError)` - Metrics retrieval failed (rare)
 * 
 * # Example
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * 
 * interface CacheMetrics {
 * hits: number;              // Cache hits
 * misses: number;            // Cache misses
 * totalTimeSavedMs: number;  // Time saved (ms)
 * hitRate: number;           // Hit rate 0.0-1.0
 * }
 * 
 * // Get cache metrics
 * const metrics = await invoke<CacheMetrics>('get_cache_metrics');
 * console.log(`Cache efficiency: ${(metrics.hitRate * 100).toFixed(1)}%`);
 * console.log(`Performance gain: ${metrics.totalTimeSavedMs}ms`);
 * 
 * // Periodic metrics collection
 * setInterval(async () => {
 * const metrics = await invoke<CacheMetrics>('get_cache_metrics');
 * logMetrics('cache.hits', metrics.hits);
 * logMetrics('cache.misses', metrics.misses);
 * logMetrics('cache.hit_rate', metrics.hitRate);
 * }, 60000); // Every minute
 * 
 * // Display compact metrics
 * updateMetricsBar({
 * hits: metrics.hits,
 * hitRate: `${(metrics.hitRate * 100).toFixed(0)}%`
 * });
 * ```
 * 
 * # Metrics Breakdown
 * 
 * - **hits**: Number of cache hits since startup
 * - **misses**: Number of cache misses since startup
 * - **total_time_saved_ms**: Estimated time saved by cache
 * - **hit_rate**: hits / (hits + misses), 0.0 to 1.0
 * 
 * # Difference from get_cache_stats
 * 
 * - **Lighter**: Excludes size/capacity information
 * - **Focused**: Performance metrics only
 * - **Use Case**: Frequent polling, metrics dashboards
 * 
 * # Performance
 * 
 * - **Access Time**: ~1μs (atomic counter reads)
 * - **No Locking**: Lock-free atomic operations
 * - **Synchronous**: Instant return
 * 
 * # Architecture
 * 
 * Direct accessor to global QUERY_CACHE singleton metrics
 */
async getCacheMetrics() : Promise<Result<CacheMetrics, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_cache_metrics") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Manually clears all cached search results
 * 
 * Removes all entries from the in-memory search cache, forcing subsequent searches
 * to regenerate embeddings and query the database. Cache is automatically cleared
 * after indexing operations, but manual clearing may be useful for testing or
 * troubleshooting.
 * 
 * # Returns
 * 
 * * `Ok(())` - Cache cleared successfully
 * * `Err(AppError)` - Cache clear failed (rare)
 * 
 * # Example
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * 
 * // Clear cache manually
 * await invoke('clear_search_cache');
 * console.log('Search cache cleared');
 * 
 * // Clear cache after settings change
 * const handleSettingsChange = async () => {
 * await updateSettings();
 * await invoke('clear_search_cache'); // Force fresh results
 * refreshSearchResults();
 * };
 * 
 * // Clear cache button
 * const handleClearCache = async () => {
 * await invoke('clear_search_cache');
 * showNotification('Cache cleared. Next search will be fresh.');
 * };
 * ```
 * 
 * # Side Effects
 * 
 * - All cached search results removed
 * - Next searches will be slower (no cache hits)
 * - Cache metrics reset to 0
 * 
 * # Use Cases
 * 
 * - **Testing**: Verify search behavior without cache
 * - **Troubleshooting**: Clear stale cache entries
 * - **Settings Changes**: Force fresh results after config changes
 * - **Manual Maintenance**: User-initiated cache clearing
 * 
 * # Performance
 * 
 * - **Clear Time**: ~1-10ms (depends on cache size)
 * - **Thread-Safe**: Locked operation
 * - **Synchronous**: Blocks until complete
 * 
 * # Architecture
 * 
 * Direct accessor to global QUERY_CACHE singleton
 */
async clearSearchCache() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_search_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unified cache operation dispatcher using enum-based pattern
 * 
 * Single command handling multiple cache operations (clear, stats, metrics) via enum
 * dispatch pattern. Simplifies frontend API by consolidating related operations.
 * 
 * # Arguments
 * 
 * * `operation` - Enum specifying the operation to perform
 * 
 * # Returns
 * 
 * * `Ok(CacheResponse)` - Operation-specific response (Cleared/Stats/Metrics)
 * * `Err(AppError)` - Cache operation failed (rare)
 * 
 * # Example
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * 
 * // Clear cache
 * const clearResult = await invoke('cache_operation', {
 * operation: { action: 'clear' }
 * });
 * console.log('Cache cleared');
 * 
 * // Get stats
 * const statsResult = await invoke<{ type: 'stats', data: CacheStats }>('cache_operation', {
 * operation: { action: 'getStats' }
 * });
 * console.log('Cache size:', statsResult.data.size);
 * console.log('Hit rate:', statsResult.data.hitRate);
 * 
 * // Get metrics
 * const metricsResult = await invoke<{ type: 'metrics', data: CacheMetrics }>('cache_operation', {
 * operation: { action: 'getMetrics' }
 * });
 * console.log('Hits:', metricsResult.data.hits);
 * console.log('Time saved:', metricsResult.data.totalTimeSavedMs, 'ms');
 * ```
 * 
 * # Performance
 * 
 * - **Clear**: ~1-10ms (depends on cache size)
 * - **Stats/Metrics**: ~1μs (atomic reads)
 * - **Synchronous**: Instant return
 * 
 * # Architecture
 * 
 * Enum dispatch pattern for unified API (alternative to separate commands)
 */
async cacheOperation(operation: CacheOperation) : Promise<Result<CacheResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cache_operation", { operation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async embeddingOperation(operation: EmbeddingOperation) : Promise<Result<EmbeddingResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("embedding_operation", { operation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateEmbedding(text: string) : Promise<Result<number[], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_embedding", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateEmbeddingsBatch(texts: string[]) : Promise<Result<number[][], ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_embeddings_batch", { texts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEmbeddingModelInfo() : Promise<Result<ModelInfo, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_embedding_model_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setHuggingfaceToken(token: string) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_huggingface_token", { token }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHuggingfaceTokenStatus() : Promise<Result<HfTokenStatus, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_huggingface_token_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHuggingfaceToken() : Promise<Result<string | null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_huggingface_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHuggingfaceToken() : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_huggingface_token") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async parseWikilinks(text: string, sourcePath: string | null) : Promise<Result<ParsedLinksResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("parse_wikilinks", { text, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async extractDocumentTitle(content: string) : Promise<Result<string | null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_document_title", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveWikilink(target: string, sourcePath: string, availableDocuments: DocumentRefDto[]) : Promise<Result<ResolveLinkResponse, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_wikilink", { target, sourcePath, availableDocuments }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async extractAndResolveLinks(documentId: string, content: string) : Promise<Result<ExtractAndResolveResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("extract_and_resolve_links", { documentId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createConversation(request: CreateConversationRequestDto) : Promise<Result<CreateConversationResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_conversation", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversation(request: GetConversationRequestDto) : Promise<Result<GetConversationResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversation", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listConversations(query: ListConversationsQuery) : Promise<Result<ListConversationsResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_conversations", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteConversation(request: DeleteConversationRequestDto) : Promise<Result<DeleteConversationResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_conversation", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConversationMessages(request: GetConversationMessagesRequestDto) : Promise<Result<GetConversationMessagesResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conversation_messages", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameConversation(request: RenameConversationRequestDto) : Promise<Result<RenameConversationResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_conversation", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async batchImportFiles(request: StartBatchFileImportRequestDto) : Promise<Result<StartBatchFileImportResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_import_files", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async batchImportUrls(request: StartBatchUrlImportRequestDto) : Promise<Result<StartBatchUrlImportResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("batch_import_urls", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBatchStatus(request: GetBatchJobStatusRequestDto) : Promise<Result<BatchJobStatusDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_batch_status", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelBatch(request: CancelBatchJobRequestDto) : Promise<Result<CancelBatchJobResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_batch", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getBatchHistory(request: ListBatchJobsRequestDto) : Promise<Result<ListBatchJobsResponseDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_batch_history", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginCreateBackup(request: CreateBackupRequestDto) : Promise<Result<CreateBackupResultDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_create_backup", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginRestoreBackup(request: RestoreBackupRequestDto) : Promise<Result<RestoreBackupResultDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_restore_backup", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginListBackups() : Promise<Result<ListBackupsResultDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_list_backups") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginExportMarkdown(request: ExportMarkdownRequestDto) : Promise<Result<ExportResultDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_export_markdown", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginExportJson(request: ExportJsonRequestDto) : Promise<Result<null, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_export_json", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginExportCsv(request: ExportCsvRequestDto) : Promise<Result<ExportResultDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_export_csv", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pluginExportHtml(request: ExportHtmlRequestDto) : Promise<Result<ExportResultDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin_export_html", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkForUpdates() : Promise<Result<UpdateInfoDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVersionInfo() : Promise<Result<VersionInfoDto, ApiError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_version_info") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActiveModels = { chat_model: DownloadedModelResponse | null; embedding_model: DownloadedModelResponse | null }
/**
 * Structured error information for API responses.
 * 
 * Contains an error code for programmatic handling, a human-readable message,
 * and optional details for debugging.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::shared::api_result::{ApiError, ErrorCode};
 * let error = ApiError {
 * code: ErrorCode::NotFound,
 * message: "Document not found".to_string(),
 * details: Some("ID: doc-123".to_string()),
 * };
 * ```
 */
export type ApiError = { 
/**
 * Error code for programmatic handling
 */
code: ErrorCode; 
/**
 * Human-readable error message
 */
message: string; 
/**
 * Optional additional details (sanitized for security)
 */
details?: string | null }
export type AppConfig = { indexedPaths: string[]; excludePatterns: string[]; autoIndex: boolean; ollamaEndpoint?: string; ollamaModel?: string }
/**
 * Main error type for the Recall application.
 * 
 * Provides user-friendly error messages and automatic conversion
 * from common error types.
 */
export type AppError = 
/**
 * I/O errors (file not found, permission denied, etc.)
 * Stores error message and kind as strings for serializability
 */
{ Io: { message: string; kind: string } } | 
/**
 * JSON serialization/deserialization errors
 * Stores error message and location for serializability
 */
{ Json: { message: string; line: number; column: number } } | 
/**
 * Database errors
 */
{ Database: string } | 
/**
 * Configuration file errors
 */
{ InvalidConfig: string } | 
/**
 * Resource not found
 */
{ NotFound: string } | 
/**
 * Permission denied
 */
{ PermissionDenied: string } | 
/**
 * Invalid input from user
 */
{ InvalidInput: string } | 
/**
 * Network errors
 */
{ Network: string } | 
/**
 * File too large to process
 */
{ FileTooLarge: { path: string; size_bytes: number; max_size_bytes: number } } | 
/**
 * File storage errors
 */
{ FileStorage: string } | 
/**
 * File not found (specific path)
 */
{ FileNotFound: { path: string } } | 
/**
 * File read error
 */
{ FileRead: { path: string; reason: string } } | 
/**
 * Embedding generation failed
 */
{ EmbeddingFailed: { reason: string } } | 
/**
 * Queue is full
 */
"QueueFull" | 
/**
 * Unsupported file type
 */
{ UnsupportedFileType: { path: string; detected_type: string } } | 
/**
 * Content extraction failed
 */
{ ContentExtraction: { path: string; reason: string } } | 
/**
 * Tokenization error
 */
{ TokenizationError: { reason: string } } | 
/**
 * Rate limit exceeded
 */
{ RateLimitExceeded: string } | 
/**
 * Invalid or corrupted data
 */
{ InvalidData: string } | 
/**
 * File system operation failed
 */
{ FileSystem: string } | 
/**
 * Invalid URL provided
 */
{ InvalidUrl: string } | 
/**
 * Invalid application state
 */
{ InvalidState: string } | 
/**
 * Storage backend error
 */
{ Storage: string } | 
/**
 * Required service is not available
 */
{ ServiceNotAvailable: string } | 
/**
 * Serialization error
 */
{ Serialization: string } | 
/**
 * Security violation or check failed
 */
{ Security: string } | 
/**
 * Keyring/credential storage error
 */
{ KeyringError: string } | 
/**
 * Validation failed
 */
{ ValidationFailed: string } | 
/**
 * Internal application error
 */
{ InternalError: string } | 
/**
 * Parsing error
 */
{ Parsing: string } | 
/**
 * Deserialization error
 */
{ Deserialization: string } | 
/**
 * Backup creation failed
 */
{ BackupCreationFailed: string } | 
/**
 * Backup restore failed
 */
{ BackupRestoreFailed: string } | 
/**
 * Backup file is corrupted
 */
{ BackupCorrupted: string } | 
/**
 * Database migration failed
 */
{ Migration: string } | 
/**
 * AI models not installed
 */
{ AiModelsNotInstalled: string } | 
/**
 * Model loading failed
 */
{ ModelLoadFailed: string } | 
/**
 * SECURITY FIX (CWE-367): Concurrent modification detected
 * Prevents TOCTOU race conditions in multi-step operations
 */
{ ConcurrentModification: { resource: string; details: string } } | 
/**
 * Domain layer error - business rule violations
 * BOXED to prevent stack overflow (DomainError is ~160 variants)
 */
{ Domain: DomainError } | 
/**
 * Application layer error - use case orchestration failures
 */
{ Application: ApplicationError } | 
/**
 * Generic error with custom message
 */
{ Other: string }
/**
 * Application errors for use cases, DTOs, and orchestration logic.
 * 
 * These errors represent failures in application-level operations such as
 * configuration, serialization, service availability, and use case execution.
 */
export type ApplicationError = 
/**
 * Domain error (business logic violation).
 * 
 * Wraps domain-level errors from aggregates, entities, and domain services.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * # use vault_desktop::domain::error::DomainError;
 * let domain_err = DomainError::EntityNotFound {
 * entity_type: "Document".to_string(),
 * identifier: "doc-123".to_string(),
 * };
 * let app_err = ApplicationError::from(domain_err);
 * assert!(app_err.is_domain_error());
 * ```
 */
{ Domain: DomainError } | 
/**
 * Invalid configuration.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::InvalidConfig {
 * details: "Missing required field 'api_key'".to_string(),
 * };
 * assert!(error.to_string().contains("api_key"));
 * assert!(error.is_config_error());
 * ```
 */
{ InvalidConfig: { details: string } } | 
/**
 * Required service is not available.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::ServiceNotAvailable {
 * service: "EmbeddingService".to_string(),
 * reason: "Model not loaded".to_string(),
 * };
 * assert!(error.to_string().contains("EmbeddingService"));
 * assert!(!error.is_config_error());
 * ```
 */
{ ServiceNotAvailable: { service: string; reason: string } } | 
/**
 * Processing queue is full (backpressure).
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::QueueFull {
 * queue_name: "indexing_queue".to_string(),
 * };
 * assert!(error.to_string().contains("indexing_queue"));
 * assert!(error.is_recoverable());
 * ```
 */
{ QueueFull: { queue_name: string } } | 
/**
 * Serialization failed.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::SerializationFailed {
 * context: "DocumentDTO".to_string(),
 * reason: "Invalid UTF-8 in field 'content'".to_string(),
 * };
 * assert!(error.to_string().contains("DocumentDTO"));
 * ```
 */
{ SerializationFailed: { context: string; reason: string } } | 
/**
 * Deserialization failed.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::DeserializationFailed {
 * context: "SearchRequest".to_string(),
 * reason: "Missing required field 'query'".to_string(),
 * };
 * assert!(error.to_string().contains("SearchRequest"));
 * ```
 */
{ DeserializationFailed: { context: string; reason: string } } | 
/**
 * JSON parsing error with location.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::JsonError {
 * message: "Expected comma".to_string(),
 * line: 42,
 * column: 15,
 * };
 * assert!(error.to_string().contains("line 42"));
 * assert!(error.to_string().contains("column 15"));
 * ```
 */
{ JsonError: { message: string; line: number; column: number } } | 
/**
 * Generic parsing error.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::ParsingError {
 * context: "CSV file".to_string(),
 * reason: "Unexpected end of file".to_string(),
 * };
 * assert!(error.to_string().contains("CSV file"));
 * ```
 */
{ ParsingError: { context: string; reason: string } } | 
/**
 * Use case execution failed.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::UseCaseFailed {
 * use_case: "IndexDocumentUseCase".to_string(),
 * reason: "Embedding generation timed out".to_string(),
 * };
 * assert!(error.to_string().contains("IndexDocumentUseCase"));
 * ```
 */
{ UseCaseFailed: { use_case: string; reason: string } } | 
/**
 * DTO mapping failed.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::application::error::ApplicationError;
 * let error = ApplicationError::MappingError {
 * context: "Document -> DocumentDTO".to_string(),
 * reason: "Missing required field".to_string(),
 * };
 * assert!(error.to_string().contains("Document -> DocumentDTO"));
 * ```
 */
{ MappingError: { context: string; reason: string } }
/**
 * Request to apply multiple tags to a document.
 */
export type ApplyTagsRequestDto = { 
/**
 * Document ID
 */
document_id: string; 
/**
 * Tag names to apply (creates tags if they don't exist)
 */
tag_names: string[] }
export type BackupInfoDto = { path: string; name: string; createdAt: string; version: string; fileCount: number; size: number }
/**
 * Options for batch import operations.
 * 
 * # Example
 * ```rust
 * use vault_desktop::application::dtos::batch_dto::BatchImportOptionsDto;
 * 
 * let options = BatchImportOptionsDto {
 * extract_article: Some(true),
 * };
 * ```
 */
export type BatchImportOptionsDto = { 
/**
 * Whether to extract article content (default: true)
 */
extractArticle?: boolean | null }
/**
 * Status of a single batch job item.
 */
export type BatchJobItemDto = { 
/**
 * Unique item ID
 */
itemId: string; 
/**
 * Target URL or file path
 */
target: string; 
/**
 * Item status: "pending", "running", "completed", "failed", "cancelled"
 */
status: string; 
/**
 * Error message if status is "failed"
 */
errorMessage?: string | null }
/**
 * Full batch job status with all items.
 * 
 * Contains detailed status for the job and each item.
 */
export type BatchJobStatusDto = { 
/**
 * Unique batch job ID
 */
jobId: string; 
/**
 * Job type: "file_import" or "url_import"
 */
jobType: string; 
/**
 * Job status: "pending", "running", "completed", "cancelled"
 */
status: string; 
/**
 * Total number of items in the batch
 */
totalItems: number; 
/**
 * Number of successfully completed items
 */
completedItems: number; 
/**
 * Number of failed items
 */
failedItems: number; 
/**
 * Job creation timestamp (ISO 8601 string)
 */
createdAt: string; 
/**
 * List of all batch items with their status
 */
items: BatchJobItemDto[] }
/**
 * Summary information for a batch job.
 * 
 * Lightweight representation for job history list.
 */
export type BatchJobSummaryDto = { 
/**
 * Unique batch job ID
 */
jobId: string; 
/**
 * Job type: "file_import" or "url_import"
 */
jobType: string; 
/**
 * Job status: "pending", "running", "completed", "cancelled"
 */
status: string; 
/**
 * Total number of items in the batch
 */
totalItems: number; 
/**
 * Number of successfully completed items
 */
completedItems: number; 
/**
 * Number of failed items
 */
failedItems: number; 
/**
 * Job creation timestamp (ISO 8601 string)
 */
createdAt: string }
export type CacheMetrics = { hits: number; misses: number; totalTimeSavedMs: number; hitRate: number }
export type CacheOperation = { action: "clear" } | { action: "getStats" } | { action: "getMetrics" }
export type CacheResponse = { type: "cleared" } | { type: "stats"; data: SearchCacheStats } | { type: "metrics"; data: CacheMetrics }
/**
 * Request to cancel a batch job.
 */
export type CancelBatchJobRequestDto = { 
/**
 * The batch job ID to cancel
 */
jobId: string }
/**
 * Response from cancelling a batch job.
 */
export type CancelBatchJobResponseDto = { 
/**
 * Number of items that were cancelled
 */
cancelledCount: number }
/**
 * Compatibility level DTO for frontend.
 */
export type CompatibilityLevelDto = 
/**
 * Model will NOT run
 */
"Incompatible" | 
/**
 * Model may run poorly
 */
"Poor" | 
/**
 * Model will run acceptably
 */
"Good" | 
/**
 * Model will run well
 */
"Excellent"
export type CompatibilityReport = { compatible: boolean; warnings: string[]; errors: string[] }
/**
 * Compatibility score DTO for frontend.
 */
export type CompatibilityScoreDto = { 
/**
 * Overall compatibility level
 */
compatibility_level: CompatibilityLevelDto; 
/**
 * Overall score (0-100)
 */
overall_score: number; 
/**
 * RAM score (0-100)
 */
ram_score: number; 
/**
 * GPU score (0-100)
 */
gpu_score: number; 
/**
 * Disk score (0-100)
 */
disk_score: number; 
/**
 * Estimated tokens/second (LLMs only)
 */
estimated_tokens_per_second: number | null; 
/**
 * Estimated loading time in seconds
 */
estimated_loading_time_seconds: number; 
/**
 * Recommendations
 */
recommendations: string[]; 
/**
 * Blockers
 */
blockers: string[] }
/**
 * Conversation representation.
 * 
 * Simple DTO for conversation data across application boundaries.
 */
export type ConversationDto = { 
/**
 * Conversation identifier
 */
id: string; 
/**
 * Conversation title
 */
title: string; 
/**
 * LLM model name (e.g., "claude-sonnet-4-5-20250929")
 */
modelName: string; 
/**
 * Optional system prompt
 */
systemPrompt: string | null; 
/**
 * Creation timestamp (ISO 8601)
 */
createdAt: string; 
/**
 * Last update timestamp (ISO 8601)
 */
updatedAt: string; 
/**
 * Number of messages in conversation
 */
messageCount: number; 
/**
 * Total tokens used
 */
totalTokens: number; 
/**
 * Space/environment identifier that owns this conversation
 */
spaceId: string | null; 
/**
 * Whether this conversation is saved to the user's shelf
 */
isSaved: boolean | null; 
/**
 * Whether this conversation is bookmarked/starred
 */
isBookmarked: boolean | null; 
/**
 * Whether this conversation is pinned in lists
 */
isPinned: boolean | null; 
/**
 * Whether this conversation is archived
 */
isArchived: boolean | null; 
/**
 * Optional timestamp when conversation was saved
 */
savedAt: string | null; 
/**
 * Optional timestamp when conversation was bookmarked
 */
bookmarkedAt: string | null; 
/**
 * Optional timestamp when conversation was pinned
 */
pinnedAt: string | null; 
/**
 * Optional timestamp when conversation was archived
 */
archivedAt: string | null; 
/**
 * Optional preview of the most recent message content
 */
lastMessagePreview: string | null }
export type CreateBackupRequestDto = { backupPath: string | null }
export type CreateBackupResultDto = { backupPath: string; size: number; createdAt: string }
/**
 * Request to create a new conversation.
 */
export type CreateConversationRequestDto = { 
/**
 * Conversation title
 */
title: string; 
/**
 * LLM model name
 */
modelName: string; 
/**
 * Optional system prompt
 */
systemPrompt: string | null }
/**
 * Response from creating a conversation.
 */
export type CreateConversationResponseDto = { 
/**
 * The created conversation
 */
conversation: ConversationDto; 
/**
 * Status message
 */
status: string }
/**
 * Request to delete a conversation.
 */
export type DeleteConversationRequestDto = { 
/**
 * Conversation identifier
 */
conversationId: string }
/**
 * Response from deleting a conversation.
 */
export type DeleteConversationResponseDto = { 
/**
 * Status message
 */
status: string }
export type DocumentRefDto = { documentId: string; filePath: string; title: string | null }
/**
 * Domain errors representing business rule violations and entity state problems.
 * 
 * These errors are thrown by domain entities, aggregates, and services when
 * business invariants are violated or invalid operations are attempted.
 */
export type DomainError = 
/**
 * Entity not found in the system.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::domain::error::DomainError;
 * let error = DomainError::EntityNotFound {
 * entity_type: "Document".to_string(),
 * identifier: "doc-123".to_string(),
 * };
 * assert!(error.to_string().contains("Document"));
 * assert!(error.to_string().contains("doc-123"));
 * ```
 */
{ EntityNotFound: { entity_type: string; identifier: string } } | 
/**
 * Entity or aggregate is in an invalid state for the requested operation.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::domain::error::DomainError;
 * let error = DomainError::InvalidState {
 * details: "Document is archived and cannot be modified".to_string(),
 * };
 * assert!(error.to_string().contains("invalid state"));
 * ```
 */
{ InvalidState: { details: string } } | 
/**
 * Field validation failed.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::domain::error::DomainError;
 * let error = DomainError::ValidationFailed {
 * field: "email".to_string(),
 * reason: "Invalid email format".to_string(),
 * };
 * assert!(error.to_string().contains("email"));
 * assert!(error.to_string().contains("Invalid email format"));
 * ```
 */
{ ValidationFailed: { field: string; reason: string } } | 
/**
 * File type is not supported for indexing or processing.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::domain::error::DomainError;
 * # use std::path::PathBuf;
 * let error = DomainError::UnsupportedFileType {
 * path: PathBuf::from("/path/to/file.xyz"),
 * detected_type: Some("application/octet-stream".to_string()),
 * };
 * assert!(error.to_string().contains("file.xyz"));
 * ```
 */
{ UnsupportedFileType: { path: string; detected_type: string | null } } | 
/**
 * File size exceeds maximum allowed size.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::domain::error::DomainError;
 * # use std::path::PathBuf;
 * let error = DomainError::FileTooLarge {
 * path: PathBuf::from("/path/to/huge.pdf"),
 * size_bytes: 100_000_000,
 * max_size_bytes: 50_000_000,
 * };
 * assert!(error.to_string().contains("100000000 bytes"));
 * assert!(error.to_string().contains("50000000 bytes"));
 * ```
 */
{ FileTooLarge: { path: string; size_bytes: number; max_size_bytes: number } } | 
/**
 * Concurrent modification detected (optimistic locking failure).
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::domain::error::DomainError;
 * let error = DomainError::ConcurrentModification {
 * resource: "Document doc-123".to_string(),
 * details: "Version mismatch: expected v2, found v3".to_string(),
 * };
 * assert!(error.to_string().contains("doc-123"));
 * assert!(error.to_string().contains("Version mismatch"));
 * ```
 */
{ ConcurrentModification: { resource: string; details: string } } | 
/**
 * Domain constraint or business rule violated.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::domain::error::DomainError;
 * let error = DomainError::ConstraintViolation {
 * constraint: "A document must have at least one chunk".to_string(),
 * };
 * assert!(error.to_string().contains("at least one chunk"));
 * ```
 */
{ ConstraintViolation: { constraint: string } }
export type DownloadModelResponse = { download_id: string; status: string }
export type DownloadStatus = { id: string; status: string; progress: number; error: string | null }
/**
 * Response for get_models_with_metadata command
 */
export type DownloadedModelResponse = { id: string; model_name: string; model_id: string; file_path: string; file_size_bytes: number; model_type: string; downloaded_at: string; last_used_at: string | null; use_count: number; is_active_for_chat: boolean; is_active_for_embedding: boolean; is_active_for_utility: boolean; 
/**
 * 'local' for downloaded files, 'ollama' for remote Ollama tags.
 */
backend: string }
/**
 * Frontend mirror of `EmbeddingCompatibility`.
 */
export type EmbeddingCompatibilityDto = 
/**
 * Model is loadable today.
 */
{ kind: "compatible"; architecture: string } | 
/**
 * Recognized architecture but not yet implemented in the local runtime.
 */
{ kind: "incompatible"; architecture: string; reason: string } | 
/**
 * We couldn't tell from tags. Treated as not-yet-supported.
 */
{ kind: "unknown" }
export type EmbeddingOperation = { action: "generateSingle"; text: string } | { action: "generateBatch"; texts: string[] } | { action: "getModelInfo" }
export type EmbeddingResponse = { type: "single"; data: number[] } | { type: "batch"; data: number[][] } | { type: "modelInfo"; data: ModelInfo }
/**
 * Comprehensive error code enumeration for API responses.
 * 
 * These codes allow the frontend to handle errors programmatically without
 * parsing error messages. Each code maps to a specific error category.
 * 
 * # Serialization
 * 
 * Error codes serialize to SCREAMING_SNAKE_CASE for consistency with typical
 * API conventions.
 * 
 * # Examples
 * 
 * ```rust
 * # use vault_desktop::shared::api_result::ErrorCode;
 * let code = ErrorCode::NotFound;
 * let json = serde_json::to_string(&code).unwrap();
 * assert_eq!(json, "\"NOT_FOUND\"");
 * ```
 */
export type ErrorCode = 
/**
 * Requested resource was not found
 */
"NOT_FOUND" | 
/**
 * Resource already exists
 */
"ALREADY_EXISTS" | 
/**
 * Resource has been deleted or is no longer available
 */
"GONE" | 
/**
 * Operation not permitted
 */
"PERMISSION_DENIED" | 
/**
 * Invalid credentials or authentication failure
 */
"UNAUTHORIZED" | 
/**
 * Security violation detected
 */
"SECURITY_VIOLATION" | 
/**
 * Input validation failed
 */
"VALIDATION_ERROR" | 
/**
 * Invalid input format
 */
"INVALID_INPUT" | 
/**
 * Invalid configuration
 */
"INVALID_CONFIG" | 
/**
 * Invalid state for requested operation
 */
"INVALID_STATE" | 
/**
 * Constraint violation
 */
"CONSTRAINT_VIOLATION" | 
/**
 * File not found
 */
"FILE_NOT_FOUND" | 
/**
 * File is too large to process
 */
"FILE_TOO_LARGE" | 
/**
 * File type not supported
 */
"UNSUPPORTED_FILE_TYPE" | 
/**
 * File system operation failed
 */
"FILE_SYSTEM_ERROR" | 
/**
 * File read error
 */
"FILE_READ_ERROR" | 
/**
 * File write error
 */
"FILE_WRITE_ERROR" | 
/**
 * Database operation failed
 */
"DATABASE_ERROR" | 
/**
 * Database connection failed
 */
"DATABASE_CONNECTION_ERROR" | 
/**
 * Database migration failed
 */
"MIGRATION_ERROR" | 
/**
 * Network operation failed
 */
"NETWORK_ERROR" | 
/**
 * Request timeout
 */
"TIMEOUT" | 
/**
 * Rate limit exceeded
 */
"RATE_LIMIT_EXCEEDED" | 
/**
 * Required service is not available
 */
"SERVICE_NOT_AVAILABLE" | 
/**
 * Service initialization failed
 */
"SERVICE_INITIALIZATION_ERROR" | 
/**
 * AI model not loaded or unavailable
 */
"MODEL_NOT_LOADED" | 
/**
 * AI model loading failed
 */
"MODEL_LOAD_ERROR" | 
/**
 * Data processing failed
 */
"PROCESSING_ERROR" | 
/**
 * Serialization failed
 */
"SERIALIZATION_ERROR" | 
/**
 * Deserialization failed
 */
"DESERIALIZATION_ERROR" | 
/**
 * Parsing error
 */
"PARSING_ERROR" | 
/**
 * Embedding generation failed
 */
"EMBEDDING_ERROR" | 
/**
 * Content extraction failed
 */
"EXTRACTION_ERROR" | 
/**
 * Tokenization error
 */
"TOKENIZATION_ERROR" | 
/**
 * Concurrent modification detected
 */
"CONCURRENT_MODIFICATION" | 
/**
 * Processing queue is full
 */
"QUEUE_FULL" | 
/**
 * Backup creation failed
 */
"BACKUP_CREATION_FAILED" | 
/**
 * Backup restore failed
 */
"BACKUP_RESTORE_FAILED" | 
/**
 * Backup file is corrupted
 */
"BACKUP_CORRUPTED" | 
/**
 * Internal server error
 */
"INTERNAL_ERROR" | 
/**
 * Feature not implemented
 */
"NOT_IMPLEMENTED" | 
/**
 * Generic error
 */
"UNKNOWN"
export type ExportCsvRequestDto = { outputPath: string }
export type ExportHtmlRequestDto = { outputDir: string }
export type ExportJsonRequestDto = { outputPath: string; pretty: boolean }
export type ExportMarkdownRequestDto = { outputDir: string }
export type ExportResultDto = { count: number }
export type ExtractAndResolveResponseDto = { links: ResolvedLinkDto[] }
/**
 * Favorite document with metadata
 */
export type FavoriteDocument = { id: string; document_id: string; document_name: string; document_path: string; file_type: string | null; added_at: string }
/**
 * File metadata representation.
 * 
 * Flat DTO for file metadata including size, modified time, permissions, and MIME type.
 */
export type FileMetadataDto = { 
/**
 * File name
 */
fileName: string; 
/**
 * MIME type
 */
mimeType: string; 
/**
 * File size in bytes
 */
sizeBytes: number; 
/**
 * Last modified timestamp (ISO 8601)
 */
modifiedAt: string; 
/**
 * Whether the file is readable
 */
isReadable: boolean; 
/**
 * Whether the file is writable
 */
isWritable: boolean; 
/**
 * Full file path
 */
path: string }
/**
 * Request to generate tags for a document using LLM.
 */
export type GenerateTagsRequestDto = { 
/**
 * Document ID
 */
document_id: string; 
/**
 * Maximum number of tags to generate (default: 5)
 */
max_tags?: number }
/**
 * Request to get batch job status.
 */
export type GetBatchJobStatusRequestDto = { 
/**
 * The batch job ID to query
 */
jobId: string }
/**
 * Request to get conversation messages.
 */
export type GetConversationMessagesRequestDto = { 
/**
 * Conversation identifier
 */
conversationId: string }
/**
 * Response from getting conversation messages.
 */
export type GetConversationMessagesResponseDto = { 
/**
 * List of messages
 */
messages: MessageDto[]; 
/**
 * Total count
 */
total: number }
/**
 * Request to get a conversation by ID.
 */
export type GetConversationRequestDto = { 
/**
 * Conversation identifier
 */
conversationId: string }
/**
 * Response from getting a conversation.
 */
export type GetConversationResponseDto = { 
/**
 * The conversation (if found)
 */
conversation: ConversationDto | null }
export type HealthStatus = { status: string; database: boolean; embedding_model: boolean; llm: boolean; timestamp: string }
export type HfTokenStatus = { is_set: boolean }
/**
 * Response from indexing a file.
 * 
 * Contains the created document ID and statistics.
 */
export type IndexFileResponseDto = { 
/**
 * ID of the created document
 */
documentId: string; 
/**
 * Number of chunks created
 */
chunksCreated: number; 
/**
 * Indexing status
 */
status: string; 
/**
 * Optional error message if indexing failed
 */
error: string | null; 
/**
 * Library path where file is stored (content-addressed storage)
 */
filePath: string }
export type IndexingStatus = { active: boolean; progress: number }
export type ListBackupsResultDto = { backups: BackupInfoDto[] }
/**
 * Request to list batch jobs (paginated).
 */
export type ListBatchJobsRequestDto = { 
/**
 * Maximum number of jobs to return (default: 50, max: 100)
 */
limit?: number | null; 
/**
 * Number of jobs to skip (for pagination)
 */
offset?: number | null }
/**
 * Response containing paginated list of batch jobs.
 */
export type ListBatchJobsResponseDto = { 
/**
 * List of batch job summaries (newest first)
 */
jobs: BatchJobSummaryDto[] }
/**
 * Query parameters for listing conversations.
 */
export type ListConversationsQuery = { 
/**
 * Maximum number of conversations to return
 */
limit: number | null; 
/**
 * Offset for pagination
 */
offset: number | null }
/**
 * Response from listing conversations.
 */
export type ListConversationsResponseDto = { 
/**
 * List of conversations
 */
conversations: ConversationDto[]; 
/**
 * Total count
 */
total: number }
/**
 * Conversation message representation.
 * 
 * Simple DTO for message data across application boundaries.
 */
export type MessageDto = { 
/**
 * Message identifier
 */
id: string; 
/**
 * Conversation identifier this message belongs to
 */
conversationId: string; 
/**
 * Message role (user, assistant, system)
 */
role: string; 
/**
 * Message content
 */
content: string; 
/**
 * Token count for this message
 */
tokens: number; 
/**
 * Creation timestamp (ISO 8601)
 */
createdAt: string; 
/**
 * Optional metadata (JSON string)
 */
metadata: string | null; 
/**
 * Message status (pending/completed/failed)
 */
status: string }
export type MetadataUpdate = { tags: string[] | null; custom_fields: { [key in string]: string } | null }
/**
 * Cache statistics.
 */
export type ModelCatalogStats = { total_entries: number; valid_entries: number; expired_entries: number }
/**
 * Model category DTO for frontend.
 */
export type ModelCategoryDto = 
/**
 * Large Language Model
 */
"LLM" | 
/**
 * Embedding model
 */
"Embedding" | 
/**
 * OCR model
 */
"OCR"
/**
 * Model file metadata DTO for frontend.
 */
export type ModelFileMetadataDto = { 
/**
 * Filename
 */
filename: string; 
/**
 * Size in bytes
 */
size_bytes: number; 
/**
 * Optional checksum (SHA256)
 */
checksum: string | null; 
/**
 * Download URL
 */
url: string; 
/**
 * Whether downloaded
 */
downloaded: boolean }
export type ModelInfo = { model_name: string; dimensions: number; is_loaded: boolean }
/**
 * Model metadata DTO for frontend.
 */
export type ModelMetadataDto = { 
/**
 * Unique model identifier
 */
id: string; 
/**
 * Human-readable name
 */
name: string; 
/**
 * Model category
 */
category: ModelCategoryDto; 
/**
 * Description
 */
description: string; 
/**
 * Size in GB
 */
size_gb: number; 
/**
 * Minimum RAM in GB
 */
minimum_ram_gb: number; 
/**
 * Recommended RAM in GB
 */
recommended_ram_gb: number; 
/**
 * Context length in tokens
 */
context_length: number; 
/**
 * Performance tier
 */
performance_tier: PerformanceTierDto; 
/**
 * Supported quantizations
 */
supported_quantizations: string[]; 
/**
 * Capabilities
 */
capabilities: string[]; 
/**
 * Download URL (deprecated)
 */
download_url: string | null; 
/**
 * License
 */
license: string; 
/**
 * Requires auth to download
 */
requires_auth: boolean; 
/**
 * HuggingFace model ID
 */
model_id: string | null; 
/**
 * Default GGUF filename
 */
default_filename: string | null; 
/**
 * Files for multi-file models
 */
files: ModelFileMetadataDto[]; 
/**
 * Total size in bytes
 */
total_size_bytes: number; 
/**
 * Output dimension for embedding models (e.g., 384, 768, 1024).
 * Null for non-embedding models.
 */
embedding_dimensions: number | null; 
/**
 * Compatibility verdict for embedding models. Null for non-embedding
 * models. Frontend uses this to disable + badge incompatible rows so
 * users don't waste a 1GB+ download on a model that won't load.
 */
embedding_compatibility: EmbeddingCompatibilityDto | null }
/**
 * Model recommendation DTO for frontend.
 */
export type ModelRecommendationDto = { 
/**
 * Model metadata
 */
model: ModelMetadataDto; 
/**
 * Compatibility analysis
 */
compatibility: CompatibilityScoreDto; 
/**
 * Ranking score (0-100)
 */
ranking_score: number; 
/**
 * Popularity metric from upstream provider (downloads)
 */
popularity_downloads?: number | null; 
/**
 * Popularity metric from upstream provider (likes)
 */
popularity_likes?: number | null }
/**
 * Model search result DTO for frontend.
 */
export type ModelSearchResultDto = { 
/**
 * Model metadata
 */
model: ModelMetadataDto; 
/**
 * Relevance score (0-100)
 */
relevance_score: number; 
/**
 * Model source
 */
source: ModelSourceDto; 
/**
 * Popularity metric from upstream provider (downloads)
 */
popularity_downloads?: number | null; 
/**
 * Popularity metric from upstream provider (likes)
 */
popularity_likes?: number | null }
/**
 * Model source DTO for frontend.
 */
export type ModelSourceDto = 
/**
 * Curated internal catalog
 */
"Curated" | 
/**
 * External API (Hugging Face)
 */
"External"
/**
 * Response for wikilink parsing (for frontend compatibility).
 */
export type ParsedLinksResponse = { links: WikiLinkDto[]; count: number }
/**
 * Performance tier DTO for frontend.
 */
export type PerformanceTierDto = 
/**
 * Fast models (< 2s/response)
 */
"Fast" | 
/**
 * Balanced speed/quality (2-5s/response)
 */
"Balanced" | 
/**
 * Accurate models (> 5s/response)
 */
"Accurate"
/**
 * Recency search options for time-aware search.
 * 
 * Boosts recent documents in search results.
 */
export type RecencySearchOptions = { 
/**
 * The search query text
 */
query: string; 
/**
 * Maximum number of results
 */
limit: number | null; 
/**
 * Weight for recency boost (0.0 to 1.0)
 */
recencyWeight: number | null; 
/**
 * Maximum age in days to consider
 */
maxAgeDays: number | null }
/**
 * Request to remove a tag from a document.
 */
export type RemoveTagRequestDto = { 
/**
 * Document ID
 */
document_id: string; 
/**
 * Tag ID to remove
 */
tag_id: string }
/**
 * Request to rename a conversation.
 */
export type RenameConversationRequestDto = { 
/**
 * Conversation identifier
 */
conversationId: string; 
/**
 * New title
 */
newTitle: string }
/**
 * Response from renaming a conversation.
 */
export type RenameConversationResponseDto = { 
/**
 * Status message
 */
status: string }
/**
 * Response for link resolution (for frontend compatibility).
 */
export type ResolveLinkResponse = { resolvedPath: string | null }
export type ResolvedLinkDto = { link: WikiLinkDto; resolvedDocumentId: string | null; confidence: number }
export type RestoreBackupRequestDto = { backupPath: string }
export type RestoreBackupResultDto = { success: boolean; restoredCount: number; message: string | null }
export type SearchCacheStats = { size: number; capacity: number; hits: number; misses: number; totalTimeSavedMs: number; hitRate: number }
/**
 * Request to search external model catalogs.
 */
export type SearchModelCatalogRequest = { 
/**
 * Search query (model name, keywords)
 */
query: string; 
/**
 * Optional category filter
 */
category: string | null; 
/**
 * Maximum size in GB
 */
max_size_gb: number | null; 
/**
 * Required capabilities
 */
required_capabilities?: string[]; 
/**
 * Maximum number of results
 */
limit?: number }
/**
 * Individual search result.
 * 
 * Flat representation of a search result for JSON serialization.
 */
export type SearchResultDto = { 
/**
 * Result identifier (chunk ID or document ID)
 */
id: string; 
/**
 * Document title or filename
 */
title: string; 
/**
 * Content snippet or preview
 */
content: string; 
/**
 * Relevance score (0.0 to 1.0)
 */
score: number; 
/**
 * Optional file path
 */
path: string | null; 
/**
 * Optional parent document ID (for chunk results)
 */
documentId: string | null; 
/**
 * Optional position within document
 */
position: number | null; 
/**
 * Optional vector similarity score
 */
vectorScore: number | null; 
/**
 * Optional BM25 keyword score
 */
bm25Score: number | null; 
/**
 * Optional vector search rank
 */
vectorRank: number | null; 
/**
 * Optional BM25 search rank
 */
bm25Rank: number | null }
/**
 * Request to start a batch file import job.
 * 
 * Accepts 1-100 file paths for batch processing.
 */
export type StartBatchFileImportRequestDto = { 
/**
 * List of file paths to import (1-100 files).
 */
filePaths: string[] }
/**
 * Response after starting a batch file import job.
 * 
 * Contains the job ID for status tracking.
 */
export type StartBatchFileImportResponseDto = { 
/**
 * Unique identifier for the batch job.
 */
jobId: string }
/**
 * Request to start a batch URL import job.
 * 
 * Creates a batch job that processes multiple URLs concurrently.
 * 
 * # Example
 * ```rust,no_run
 * use vault_desktop::application::dtos::batch_dto::{
 * StartBatchUrlImportRequestDto, BatchImportOptionsDto
 * };
 * 
 * let request = StartBatchUrlImportRequestDto {
 * urls: vec![
 * "https://example.com/article1".to_string(),
 * "https://example.com/article2".to_string(),
 * ],
 * options: Some(BatchImportOptionsDto {
 * extract_article: Some(true),
 * }),
 * };
 * ```
 */
export type StartBatchUrlImportRequestDto = { 
/**
 * List of URLs to import (1-50 URLs)
 */
urls: string[]; 
/**
 * Optional import options
 */
options?: BatchImportOptionsDto | null }
/**
 * Response from starting a batch URL import.
 * 
 * Contains the job ID for tracking progress.
 */
export type StartBatchUrlImportResponseDto = { 
/**
 * Unique batch job ID for tracking
 */
jobId: string }
/**
 * System capabilities response.
 */
export type SystemCapabilitiesResponse = { total_ram_gb: number; cpu_cores: number; cpu_architecture: string; gpu_type: string; gpu_acceleration: string; vram_gb: number | null; available_disk_gb: number }
export type SystemStats = { total_documents: number; total_chunks: number; total_tags: number; storage_size_bytes: number }
/**
 * Tag representation.
 * 
 * Simple DTO for tag data across application boundaries.
 */
export type TagDto = { 
/**
 * Tag identifier
 */
id: string; 
/**
 * Tag name
 */
name: string; 
/**
 * Optional color for UI display (hex color code)
 */
color: string | null; 
/**
 * Optional description
 */
description: string | null }
/**
 * Tag with document count.
 */
export type TagWithCountDto = { 
/**
 * Tag identifier
 */
id: string; 
/**
 * Tag name
 */
name: string; 
/**
 * Optional color for UI display (hex color code)
 */
color: string | null; 
/**
 * Creation timestamp
 */
created_at: string; 
/**
 * Number of documents with this tag
 */
document_count: number }
export type UpdateInfoDto = { available: boolean; currentVersion: string; latestVersion: string | null; downloadUrl: string | null; releaseNotes: string | null }
export type VersionInfoDto = { version: string; buildDate: string | null; commitHash: string | null }
export type WikiLinkDto = { target: string; displayText: string | null; header: string | null; lineNumber: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
