#!/usr/bin/env python3
"""Build `evals/retrieval/synthetic-library-v3.json` deterministically.

v2 is 75 short, clean documents and the production pipeline answers it at 0.97
recall@5, so it cannot tell a chunking, reranking or fusion change apart from
noise. v3 is a messy vault: long documents with a needle at an arbitrary depth,
near-identical weekly notes, OCR damage, tables, fragments, five languages, and
facts that need two documents to assemble.

The corpus is composed from the pools in `synthetic_library_v3_data.py` rather
than written out by hand, so the same seed always produces the same bytes. Run
it with no arguments to rewrite the fixture in place:

    python3 scripts/build_synthetic_library_v3.py

Integrity is enforced here rather than trusted. Every needle fact carries
distinctive tokens, and the build fails unless each token occurs in exactly the
documents the query marks relevant. Unanswerable queries carry tokens that must
occur nowhere. Queries may not quote their own answer passage, except in the
identifier dimension where quoting the identifier is the point.
"""
import argparse
import json
import re
import random
import sys
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from rag_eval import validate_dataset  # noqa: E402
from eval_integrity import digest, unique_records  # noqa: E402
import synthetic_library_v3_data as D  # noqa: E402

SEED = "lattice-synthetic-library-v3/2026-09-18"
OUTPUT = Path(__file__).resolve().parents[1] / "evals/retrieval/synthetic-library-v3.json"

NAME = "lattice-synthetic-library-v3"
DESCRIPTION = (
    "Rowan Selke's vault at Quillon Grid: long handbooks, contracts and transcripts whose "
    "answer is one buried paragraph; weekly note series that differ by a single owner, date or "
    "reversed decision; policies at three versions; OCR-damaged scans with repeated page "
    "furniture; markdown and CSV tables; German, Spanish, Russian, Japanese and Chinese notes; "
    "one-line fragments with wikilinks; and facts that only two documents together can answer. "
    "Generated by scripts/build_synthetic_library_v3.py from a fixed seed; every needle is "
    "proved unique to its relevant documents at build time. Answerable queries also carry "
    "`answer_spans`, the UTF-8 byte range of the passage that answers them."
)

DIMENSIONS = [
    # kept from v2 so the two fixtures can be read side by side
    "semantic paraphrase",
    "near-duplicate distractors",
    "current versus superseded policy",
    "graded and multi-document relevance",
    "multilingual and cross-lingual retrieval",
    "negation and exception handling",
    "exact identifiers and numeric distinctions",
    "long-context tail facts",
    "unanswerable questions",
    "topical hard negatives",
    "entity collisions",
    "scope and applicability boundaries",
    # new in v3
    "buried needle in long document",
    "multi-hop composition",
    "noisy and OCR text",
    "tables and structured content",
    "short fragment notes",
]

PARAPHRASE = "semantic paraphrase"
NEAR_DUP = "near-duplicate distractors"
SUPERSEDED = "current versus superseded policy"
MULTI_DOC = "graded and multi-document relevance"
MULTILINGUAL = "multilingual and cross-lingual retrieval"
NEGATION = "negation and exception handling"
IDENTIFIER = "exact identifiers and numeric distinctions"
TAIL = "long-context tail facts"
UNANSWERABLE_TAG = "unanswerable questions"
HARD_NEG = "topical hard negatives"
COLLISION = "entity collisions"
SCOPE = "scope and applicability boundaries"
BURIED = "buried needle in long document"
MULTIHOP = "multi-hop composition"
NOISY = "noisy and OCR text"
TABLES = "tables and structured content"
FRAGMENT = "short fragment notes"

MIN_PER_DIMENSION = 12
MAX_QUOTED_CHARACTERS = 36


def rng_for(name):
    """A stream per section, so adding a section does not reshuffle the others."""
    return random.Random(f"{SEED}#{name}")


SLOT = re.compile(r"\{(\w+)(?::(\d+)-(\d+))?\}")
CONSTANTS = {"COMPANY": D.COMPANY, "OWNER": D.OWNER, "PARTNER": D.PARTNER, "HOUSE": D.HOUSE}


def fill(template, rng, **extra):
    def replace(match):
        name, low, high = match.group(1), match.group(2), match.group(3)
        if name in extra:
            return str(extra[name])
        if name in CONSTANTS:
            return CONSTANTS[name]
        if low is not None:
            return str(rng.randint(int(low), int(high)))
        return rng.choice(D.POOLS[name])
    return SLOT.sub(replace, template)


def sentence(template, rng, **extra):
    text = fill(template, rng, **extra)
    return text[:1].upper() + text[1:]


def paragraph(rng, templates, low=3, high=6, **extra):
    # Sampled rather than chosen, so one paragraph never repeats a template.
    count = min(rng.randint(low, high), len(templates))
    return " ".join(sentence(template, rng, **extra)
                    for template in rng.sample(templates, count))


def prose(rng, templates, paragraphs, low=3, high=6, **extra):
    return [paragraph(rng, templates, low, high, **extra) for _ in range(paragraphs)]


BANNED_SUBSTRINGS = " ".join(
    [value for values in D.POOLS.values() for value in values]
    + D.OPS_SENTENCES + D.HR_SENTENCES + D.LEGAL_SENTENCES + D.MEETING_SENTENCES
    + D.JOURNAL_SENTENCES + D.READING_SENTENCES + D.RECIPE_SENTENCES + D.HOME_SENTENCES
    + D.CHAT_LINES + D.HEADING_PARTS + D.HEADING_SECTIONS + D.HEADING_SUBS
    + [D.COMPANY, D.OWNER, D.PARTNER, D.HOUSE]
).lower()

# Strings the corpus must never contain, either because an unanswerable query
# asks about them or because they are deliberate filler that a mint could
# otherwise collide with.
RESERVED = [
    "ERR-0001", "PO-00001", "TCK-0001", "QG-000-001", "QG-000-000", "SIG-00001",
    "v1.0.1", "2099-12-31", "0.0999 mm", "£0,000.00",
    "Zennerloft", "Marbleau", "Quinstock", "Verrowfen",
    "Hastermill", "Oddingbrae", "Pilcrane", "Tullowmere",
]


class Tokens:
    """Mints every distinctive string in the corpus.

    Two rules make the uniqueness check meaningful: no token repeats, and no
    token is a substring of another. Without the second rule a search for
    `ERR-4012` would also match `ERR-40128` and the check would be a lie.
    """

    def __init__(self, rng):
        self.rng = rng
        self.issued = list(RESERVED)

    def _keep(self, token):
        for other in self.issued:
            if token in other or other in token:
                return False
        self.issued.append(token)
        return True

    def _mint(self, make, attempts=6000):
        for _ in range(attempts):
            token = make()
            if self._keep(token):
                return token
        raise RuntimeError("token space exhausted")

    def error_code(self):
        return self._mint(lambda: f"ERR-{self.rng.randint(1000, 9999)}")

    def purchase_order(self):
        return self._mint(lambda: f"PO-{self.rng.randint(10000, 99999)}")

    def ticket(self):
        return self._mint(lambda: f"TCK-{self.rng.randint(1000, 9999)}")

    def signal(self):
        return self._mint(lambda: f"SIG-{self.rng.randint(10000, 99999)}")

    def part(self):
        return self._mint(lambda: f"QG-{self.rng.randint(100, 999)}-{self.rng.randint(100, 999)}")

    def release(self):
        return self._mint(
            lambda: f"v{self.rng.randint(2, 9)}.{self.rng.randint(1, 9)}.{self.rng.randint(1, 9)}")

    def date(self):
        return self._mint(
            lambda: f"20{self.rng.randint(25, 34)}-{self.rng.randint(1, 12):02d}-"
                    f"{self.rng.randint(10, 28)}")

    def amount(self):
        # One leading digit everywhere, so no amount can be a substring of another.
        return self._mint(
            lambda: f"£{self.rng.randint(1, 9)},{self.rng.randint(100, 999)}."
                    f"{self.rng.randint(10, 99)}")

    def percent(self):
        # Two integer digits for the same reason.
        return self._mint(lambda: f"{self.rng.randint(11, 89)}.{self.rng.randint(1, 9)} per cent")

    def duration(self, unit=None):
        units = [unit] if unit else ["working days", "calendar days", "hours", "weeks"]
        return self._mint(lambda: f"{self.rng.randint(11, 89)} {self.rng.choice(units)}")

    def measure(self):
        return self._mint(lambda: f"0.0{self.rng.randint(100, 998)} mm")

    ONSETS = ["br", "dr", "fl", "gr", "kr", "pl", "sl", "thr", "tr", "vr", "wr",
              "b", "d", "f", "g", "h", "k", "m", "n", "p", "r", "s", "t", "v", "z"]
    NUCLEI = ["a", "e", "i", "o", "u", "ae", "ea", "ei", "oa", "ou"]
    CODAS = ["ck", "dge", "ft", "ld", "lm", "mb", "nd", "ng", "nt", "rk", "rn",
             "sk", "sp", "st", "th", "ll", "ss", "x"]
    SUFFIXES = ["", "", "ley", "worth", "by", "mere", "ford", "hollow", "stead", "gate", "wick"]

    def anchor(self):
        """A pronounceable invented proper noun that occurs nowhere else."""
        for _ in range(20000):
            word = (self.rng.choice(self.ONSETS) + self.rng.choice(self.NUCLEI)
                    + self.rng.choice(self.CODAS) + self.rng.choice(self.SUFFIXES)).capitalize()
            if len(word) < 7 or word.lower() in BANNED_SUBSTRINGS:
                continue
            if self._keep(word):
                return word
        raise RuntimeError("anchor space exhausted")

    def of_kind(self, kind):
        return {"duration": self.duration, "amount": self.amount, "date": self.date,
                "percent": self.percent, "code": self.error_code,
                "release": self.release, "signal": self.signal}[kind]()


@dataclass
class Doc:
    id: str
    title: str
    kind: str
    collection: str
    language: str = "en"
    effective_date: str = None
    separator: str = "\n\n"
    blocks: list = field(default_factory=list)
    marks: dict = field(default_factory=dict)
    meta: dict = field(default_factory=dict)
    text: str = ""
    spans: dict = field(default_factory=dict)

    def add(self, block):
        self.blocks.append(block)
        return len(self.blocks) - 1

    def extend(self, blocks):
        for block in blocks:
            self.add(block)

    def mark(self, key, block):
        """Append a needle block and remember where it landed."""
        index = self.add(block)
        self.marks[key] = index
        return index

    def mark_at(self, key, block, index):
        """Insert a needle block at a chosen depth, keeping earlier marks valid."""
        self.blocks.insert(index, block)
        for existing, position in list(self.marks.items()):
            if position >= index:
                self.marks[existing] = position + 1
        self.marks[key] = index
        return index

    def passage(self, key):
        return self.blocks[self.marks[key]]

    def finalize(self):
        self.text = self.separator.join(self.blocks)
        offsets, running = [], 0
        for block in self.blocks:
            offsets.append(running)
            running += len(block) + len(self.separator)
        for key, index in self.marks.items():
            start = offsets[index]
            end = start + len(self.blocks[index])
            self.spans[key] = (
                len(self.text[:start].encode("utf-8")),
                len(self.text[:end].encode("utf-8")),
            )

    def record(self):
        row = {"id": self.id, "title": self.title, "kind": self.kind,
               "collection": self.collection, "language": self.language}
        if self.effective_date:
            row["effective_date"] = self.effective_date
        row["text"] = self.text
        return row


class Library:
    def __init__(self):
        self.docs = []
        self.by_id = {}
        self.queries = []
        self.query_ids = set()
        self.needles = []
        self.absent = []
        self.tokens = Tokens(rng_for("tokens"))

    def add(self, doc):
        if doc.id in self.by_id:
            raise ValueError(f"duplicate document id {doc.id}")
        self.docs.append(doc)
        self.by_id[doc.id] = doc
        return doc

    def pick(self, prefix, predicate=None):
        return [d for d in self.docs
                if d.id.startswith(prefix) and (predicate is None or predicate(d))]

    def needle(self, tokens, doc_ids):
        """Assert later that each token occurs in exactly these documents."""
        self.needles.append({"tokens": list(tokens), "docs": sorted(doc_ids)})

    def ask(self, qid, text, category, dimensions, relevance, spans=None, exempt=False):
        if qid in self.query_ids:
            raise ValueError(f"duplicate query id {qid}")
        self.query_ids.add(qid)
        self.queries.append({
            "id": qid, "text": text, "category": category,
            "dimensions": list(dict.fromkeys(dimensions)),
            "relevance": dict(relevance), "spans": spans or {}, "exempt": exempt,
        })

    def finalize(self):
        for doc in self.docs:
            doc.finalize()

    def dataset(self):
        queries = []
        for query in self.queries:
            row = {"id": query["id"], "category": query["category"],
                   "dimensions": query["dimensions"], "text": query["text"],
                   "relevance": query["relevance"]}
            spans = {}
            for doc_id, keys in sorted(query["spans"].items()):
                spans[doc_id] = [list(self.by_id[doc_id].spans[key]) for key in keys]
            if spans:
                row["answer_spans"] = spans
            queries.append(row)
        return {
            "name": NAME,
            "description": DESCRIPTION,
            "dimensions": DIMENSIONS,
            "documents": [doc.record() for doc in self.docs],
            "queries": queries,
        }


# --- OCR damage ---------------------------------------------------------------

CONFUSIONS = [("rn", "m"), ("m", "rn"), ("l", "1"), ("1", "l"), ("O", "0"), ("0", "O"),
              ("cl", "d"), ("c", "e"), ("s", "5"), ("B", "8"), ("g", "9"), ("ii", "n")]


def ocr_damage(text, rng, protect=(), rate=0.014, page_every=900):
    """Corrupt a scan the way a cheap OCR pass does, leaving protected tokens intact.

    A real scan damages the identifier as often as the prose, but a fixture whose
    needle token has been mangled cannot be proved unique, so the tokens survive
    and everything around them does not.
    """
    pieces, index = [], 0
    matches = sorted((m for token in protect for m in re.finditer(re.escape(token), text)),
                     key=lambda m: m.start())
    for match in matches:
        if match.start() < index:
            continue
        pieces.append((text[index:match.start()], True))
        pieces.append((match.group(0), False))
        index = match.end()
    pieces.append((text[index:], True))
    joined = "".join(_damage_chunk(chunk, rng, rate) if mutable else chunk
                     for chunk, mutable in pieces)
    return _paginate(joined, page_every)


def _damage_chunk(text, rng, rate):
    out, index = [], 0
    while index < len(text):
        if rng.random() < rate:
            roll = rng.random()
            if roll < 0.55:
                for source, target in CONFUSIONS:
                    if text.startswith(source, index):
                        out.append(target)
                        index += len(source)
                        break
                else:
                    out.append(text[index])
                    index += 1
            elif roll < 0.75 and text[index] == " ":
                index += 1  # dropped space
            elif roll < 0.9 and text[index].isalpha() and index + 3 < len(text):
                out.append(text[index] + "-\n")  # hyphenation across a line break
                index += 1
            else:
                out.append(text[index] * 2)  # doubled character
                index += 1
        else:
            out.append(text[index])
            index += 1
    return "".join(out)


def _paginate(text, page_every):
    """Repeat the same scanner header and footer every notional page."""
    header = "[ QG-ARC scan | Quillon Grid internal | page %d ]"
    footer = "-- end of page %d -- do not remove from site --"
    out, page, index = [], 1, 0
    while index < len(text):
        cut = text.find(" ", index + page_every)
        cut = len(text) if cut < 0 else cut
        out.append(header % page)
        out.append(text[index:cut].strip())
        out.append(footer % page)
        index, page = cut, page + 1
    return "\n".join(out)


# --- documents ----------------------------------------------------------------

SYMPTOMS = [
    ("request quota exhaustion", "ingest-fanout", "the quota broker"),
    ("lease takeover storm", "shard-marshal", "the lease keeper"),
    ("replay cursor stall", "replay-quill", "the replay cursor"),
    ("admission gate flapping", "tenant-broker", "the admission gate"),
    ("checkpoint reaper backlog", "signal-vault", "the checkpoint reaper"),
    ("probe registration drift", "probe-registry", "the schema latch"),
    ("tariff settlement mismatch", "tariff-ledger", "the offset ledger"),
    ("edge uplink brownout", "edge-warden", "the fan-in buffer"),
    ("index compaction debt", "signal-vault", "the index compactor"),
    ("span collation gaps", "ingest-fanout", "the span collator"),
    ("drain valve stuck open", "shard-marshal", "the drain valve"),
    ("warm pool exhaustion", "tenant-broker", "the retry shim"),
    ("clock skew on ingest", "probe-registry", "the span collator"),
    ("duplicate settlement batch", "tariff-ledger", "the schema latch"),
    ("cold shard promotion", "shard-marshal", "the index compactor"),
    ("tenant bucket contention", "tenant-broker", "the quota broker"),
    ("field tablet sync failure", "edge-warden", "the lease keeper"),
    ("retry storm after deploy", "ingest-fanout", "the retry shim"),
    ("silent probe dropout", "probe-registry", "the drain valve"),
    ("ledger replay divergence", "replay-quill", "the offset ledger"),
]

RINGS = [("core", "the core rings"), ("edge", "the Wendover Basin edge ring")]


def build_runbooks(lib):
    rng = rng_for("runbooks")
    for index, (symptom, service, component) in enumerate(SYMPTOMS):
        for ring, ring_label in RINGS:
            doc = Doc(id=f"runbook-{ring}-{index:02d}",
                      title=f"Runbook: {symptom} on {service} ({ring_label})",
                      kind="runbook", collection="engineering/runbooks")
            code = lib.tokens.error_code()
            ticket = lib.tokens.ticket()
            threshold = lib.tokens.duration("minutes" if ring == "edge" else "seconds")
            owner = rng.choice(D.POOLS["person"])
            doc.add(f"# {doc.title}")
            doc.mark("code", f"Error code: {code}. Owner: {owner}. Standing ticket: {ticket}. "
                             f"Applies to {ring_label} only; the sibling runbook covers the "
                             f"other ring.")
            doc.add("## Symptom\n" + paragraph(rng, D.OPS_SENTENCES, 3, 4,
                                               service=service, component=component))
            doc.add("## First checks\n" + "\n".join(
                "- " + sentence(template, rng, service=service, component=component)
                for template in rng.sample(D.OPS_SENTENCES, rng.randint(3, 5))))
            doc.mark("threshold",
                     f"## Threshold\nHold the mitigation until {component} has been above its "
                     f"band for {threshold} in {ring_label}. Acting earlier on {service} hides "
                     f"the cause and the next window looks identical.")
            doc.add("## Mitigation\n" + paragraph(rng, D.OPS_SENTENCES, 3, 5,
                                                  service=service, component=component))
            doc.mark("escalation",
                     f"## Escalation\nOnce the hold expires with the band still broken, page "
                     f"{owner} and quote {ticket}. Never raise a second ticket for this: the "
                     f"standing one carries the history the next responder needs.")
            doc.extend(prose(rng, D.OPS_SENTENCES, rng.randint(2, 4), 3, 5,
                             service=service, component=component))
            lib.needle([code], [doc.id])
            lib.needle([ticket], [doc.id])
            lib.needle([threshold], [doc.id])
            doc.meta = {"symptom": symptom, "service": service, "component": component,
                        "ring": ring, "ring_label": ring_label, "code": code,
                        "ticket": ticket, "threshold": threshold, "owner": owner}
            lib.add(doc)

    core = lib.pick("runbook-core-")
    edge = lib.pick("runbook-edge-")

    for index in range(5):
        doc = core[index]
        lib.ask(f"v3-id-runbook-bare-{index:02d}", doc.meta["code"], "bare identifier",
                [IDENTIFIER], {doc.id: 3, edge[index].id: 0},
                {doc.id: ["code"]}, exempt=True)
    for index in range(5, 8):
        doc = edge[index]
        lib.ask(f"v3-id-runbook-sentence-{index:02d}",
                f"Which runbook owns {doc.meta['ticket']}, and who gets paged when it fires?",
                "identifier inside a sentence", [IDENTIFIER, PARAPHRASE],
                {doc.id: 3, core[index].id: 0}, {doc.id: ["code", "escalation"]}, exempt=True)

    for index in range(14, 17):
        edge_doc, core_doc = edge[index], core[index]
        symptom = edge_doc.meta["symptom"]
        lib.ask(f"v3-scope-runbook-edge-{index:02d}",
                f"Out on the Wendover Basin edge ring, how long do we sit on {symptom} before "
                f"acting?",
                "ring-scoped threshold", [SCOPE, HARD_NEG],
                {edge_doc.id: 3, core_doc.id: 0}, {edge_doc.id: ["threshold"]})
        lib.ask(f"v3-scope-runbook-core-{index:02d}",
                f"In the core rings, what is the wait before we mitigate {symptom}?",
                "ring-scoped threshold", [SCOPE, HARD_NEG],
                {core_doc.id: 3, edge_doc.id: 0}, {core_doc.id: ["threshold"]})

    for index in range(2):
        doc = core[index]
        lib.ask(f"v3-neg-runbook-{index:02d}",
                f"When {doc.meta['symptom']} in the core rings has not cleared by the time the "
                f"wait is over, do we open another ticket?",
                "explicit prohibition", [NEGATION, HARD_NEG],
                {doc.id: 3, edge[index].id: 0}, {doc.id: ["escalation"]})


POLICY_FAMILIES = [
    ("workstation-encryption", "Workstation encryption standard", "security standard", "duration",
     "Full-disk encryption is required on every issued laptop. Recovery keys are escrowed "
     "centrally and a device without an escrowed key is refused on the network after {value}."),
    ("snapshot-retention", "Workspace snapshot retention", "policy", "duration",
     "Workspace snapshots are retained for {value}, after which they are destroyed without "
     "further notice to the owner."),
    ("expense-receipts", "Expense receipt threshold", "policy", "amount",
     "A receipt is required for any single expense above {value}; smaller items are declared on "
     "the monthly summary."),
    ("contractor-access", "Contractor network access", "security standard", "duration",
     "A contractor account is disabled automatically {value} after its last successful sign-in "
     "unless the sponsoring manager renews it."),
    ("incident-disclosure", "Customer incident disclosure", "policy", "duration",
     "A customer-affecting incident is disclosed to the affected accounts within {value} of the "
     "incident being declared."),
    ("on-call-rest", "On-call rest entitlement", "policy", "duration",
     "An engineer paged between midnight and six is entitled to {value} of paid rest before the "
     "next scheduled shift."),
    ("data-export", "Bulk data export control", "security standard", "amount",
     "A bulk export billed above {value} requires a second approver drawn from outside the "
     "requesting team."),
    ("supplier-onboarding", "Supplier onboarding checks", "policy", "duration",
     "A new supplier may not be issued a purchase order until the checks complete, which takes "
     "{value} from the first submission."),
    ("device-loss", "Lost device reporting", "security standard", "duration",
     "A lost or stolen device is reported within {value} of the loss being noticed, at any hour."),
    ("training-refresh", "Mandatory training refresh", "policy", "duration",
     "Security awareness training is refreshed every {value}; an overdue account loses console "
     "access until it is completed."),
    ("change-freeze", "Seasonal change freeze", "policy", "duration",
     "The change freeze runs for {value} around the end of the financial year and covers every "
     "production ring."),
    ("record-disposal", "Physical record disposal", "policy", "duration",
     "Paper records leaving a site are destroyed by the approved contractor within {value} of "
     "collection."),
]


def build_policies(lib):
    rng = rng_for("policies")
    for order, (slug, title, kind, value_kind, rule) in enumerate(POLICY_FAMILIES):
        family = []
        for version in (1, 2, 3):
            value = lib.tokens.of_kind(value_kind)
            current = version == 3
            doc = Doc(id=f"policy-{slug}-v{version}",
                      title=f"{title} (version {version}.0)",
                      kind=kind if current else f"superseded {kind}",
                      collection="company/policy", effective_date=lib.tokens.date())
            doc.add(f"# {doc.title}")
            doc.add(f"Status: {'in force' if current else 'superseded'}. "
                    f"Effective {doc.effective_date}. Applies across {D.COMPANY}.")
            doc.mark("rule", "## Rule\n" + rule.replace("{value}", value))
            doc.add("## Background\n" + paragraph(rng, D.HR_SENTENCES, 3, 5))
            if current:
                exception = lib.tokens.anchor()
                doc.mark("exception",
                         f"## Exception\nThe {exception} exception suspends this rule for a site "
                         f"under a declared outage, and only for as long as that outage lasts. "
                         f"There is no other way round it: a local addendum cannot create one "
                         f"and a manager cannot grant one.")
                lib.needle([exception], [doc.id])
            doc.extend(prose(rng, D.HR_SENTENCES, rng.randint(2, 4), 3, 5))
            lib.needle([value], [doc.id])
            doc.meta = {"value": value, "version": version, "title": title, "slug": slug}
            lib.add(doc)
            family.append(doc)
        v1, v2, v3 = family

        if order < 7:
            lib.ask(f"v3-policy-current-{slug}",
                    f"What does the {title.lower()} require today?",
                    "current policy value", [SUPERSEDED, HARD_NEG],
                    {v3.id: 3, v2.id: 0, v1.id: 0}, {v3.id: ["rule"]})
        if order < 6:
            lib.ask(f"v3-policy-prior-{slug}",
                    f"Before the latest revision, what did the {title.lower()} say?",
                    "superseded policy value", [SUPERSEDED, NEAR_DUP],
                    {v2.id: 3, v3.id: 1, v1.id: 1}, {v2.id: ["rule"]})
        if order < 7:
            lib.ask(f"v3-policy-exception-{slug}",
                    f"Is there any way round the {title.lower()} other than a site outage that "
                    f"has been declared?",
                    "exception boundary", [NEGATION, SCOPE],
                    {v3.id: 3}, {v3.id: ["exception"]})


PROJECTS = ["the Garnetline migration", "the Pellum refresh", "the Sibbe rollout",
            "the Wrackford cutover", "the Dunlark pilot", "the Ostrel expansion",
            "the Harrowgate relocation", "the Drummel Flats build-out"]


def build_vendors(lib):
    rng = rng_for("vendors")
    for index, vendor in enumerate(D.POOLS["vendor"]):
        renewal = lib.tokens.date()
        notice = lib.tokens.duration()
        clause = lib.tokens.anchor()
        doc = Doc(id=f"contract-{index:02d}", title=f"Master services agreement: {vendor}",
                  kind="contract", collection="vendors/contracts",
                  effective_date=lib.tokens.date())
        doc.add(f"# Master services agreement: {vendor}")
        doc.mark("renewal", f"## Term\nThis agreement renews on {renewal} and thereafter "
                            f"annually. Either party may prevent renewal by giving {notice} of "
                            f"written notice.")
        doc.extend("## Terms\n" + paragraph(rng, D.LEGAL_SENTENCES, 4, 6)
                   for _ in range(rng.randint(3, 5)))
        doc.mark("clause", f"## The {clause} undertaking\nWhere {vendor} withdraws from a named "
                           f"site it shall continue to serve that site for the notice period, "
                           f"and shall bear the cost of any interim arrangement the customer "
                           f"reasonably makes.")
        doc.extend(prose(rng, D.LEGAL_SENTENCES, rng.randint(2, 4), 4, 6))
        lib.needle([renewal], [doc.id])
        lib.needle([notice], [doc.id])
        lib.needle([clause], [doc.id])
        doc.meta = {"vendor": vendor, "renewal": renewal, "notice": notice, "clause": clause,
                    "project": PROJECTS[index]}
        lib.add(doc)

        for order in range(2):
            po = lib.tokens.purchase_order()
            part = lib.tokens.part()
            amount = lib.tokens.amount()
            po_doc = Doc(id=f"purchase-order-{index:02d}-{order}",
                         title=f"Purchase order {po} — {vendor}",
                         kind="purchase order", collection="vendors/orders",
                         effective_date=lib.tokens.date())
            po_doc.add(f"# Purchase order {po}")
            po_doc.mark("line",
                        "| Line | Part | Description | Qty | Unit price |\n"
                        "| --- | --- | --- | ---: | ---: |\n"
                        f"| 1 | {part} | Replacement sensor head | {rng.randint(2, 40)} | "
                        f"{amount} |\n"
                        "| 2 | QG-000-000 | Carriage and handling | 1 | £0,000.00 |")
            po_doc.add(f"Raised against the {vendor} master services agreement. Delivery to "
                       f"{rng.choice(D.POOLS['site'])}. "
                       + paragraph(rng, D.LEGAL_SENTENCES, 2, 3))
            lib.needle([po], [po_doc.id])
            lib.needle([part], [po_doc.id])
            lib.needle([amount], [po_doc.id])
            po_doc.meta = {"po": po, "part": part, "amount": amount, "vendor": vendor}
            lib.add(po_doc)

    contracts = lib.pick("contract-", lambda d: d.meta.get("vendor"))
    orders = lib.pick("purchase-order-")
    for index, doc in enumerate(contracts[:5]):
        lib.ask(f"v3-contract-renewal-{index:02d}",
                f"When does the {doc.meta['vendor']} master agreement come up for renewal, and "
                f"how much notice stops it?",
                "contract term", [IDENTIFIER, MULTI_DOC],
                {doc.id: 3}, {doc.id: ["renewal"]}, exempt=True)
    for index, doc in enumerate(orders[:5]):
        lib.ask(f"v3-order-line-{index:02d}",
                f"On purchase order {doc.meta['po']}, what part number is on line one and what "
                f"is its unit price?",
                "order line lookup", [IDENTIFIER, TABLES],
                {doc.id: 3}, {doc.id: ["line"]}, exempt=True)


MEETING_SERIES = [
    ("merridew-sync", "Merridew platform sync", 13),
    ("sepwick-standup", "Sepwick field ops standup", 11),
    ("nyelle-review", "Nyelle security review", 14),
    ("tarrow-council", "Tarrow data council", 10),
]


def build_meetings(lib):
    rng = rng_for("meetings")
    people = D.POOLS["person"]
    first_meeting = date(2028, 1, 10)
    for series, (slug, title, weeks) in enumerate(MEETING_SERIES):
        docs = []
        carried = paragraph(rng, D.MEETING_SENTENCES, 2, 3)
        risks = paragraph(rng, D.MEETING_SENTENCES, 2, 3)
        for week in range(1, weeks + 1):
            owner = people[(week * 5) % len(people)]
            due = lib.tokens.date()
            signal = lib.tokens.signal()
            doc = Doc(id=f"meeting-{slug}-w{week:02d}",
                      title=f"{title} — week {week:02d}",
                      kind="meeting notes", collection="work/meetings",
                      effective_date=(first_meeting
                                      + timedelta(days=7 * (week - 1) + 140 * series)).isoformat())
            doc.add(f"# {title} — week {week:02d}")
            doc.add("Attendees: " + ", ".join(
                people[(week * 3 + offset) % len(people)] for offset in range(4)))
            doc.add("## Carried over\n" + carried)
            doc.mark("owner",
                     "## Actions\n| Action | Owner | Due |\n| --- | --- | --- |\n"
                     f"| Close out the open drift report | {owner} | {due} |\n"
                     f"| Confirm the rota for the next window | {people[week % len(people)]} | "
                     f"{due} |")
            doc.mark("signal",
                     f"## Numbers\nThe standing signal reference quoted this week was {signal}. "
                     f"Everything else in the pack was unchanged from the previous session.")
            if week == weeks - 2:
                reversal = lib.tokens.anchor()
                doc.mark("decision",
                         f"## Decision\nThe {reversal} proposal, agreed in an earlier session, "
                         f"was reversed today. The group will not proceed with it, and the "
                         f"earlier minute should be read as withdrawn.")
                lib.needle([reversal], [doc.id])
            doc.add("## Risks\n" + risks)
            doc.extend(prose(rng, D.MEETING_SENTENCES, 1, 2, 3))
            lib.needle([due], [doc.id])
            lib.needle([signal], [doc.id])
            doc.meta = {"owner": owner, "due": due, "signal": signal, "week": week}
            lib.add(doc)
            docs.append(doc)

        def graded(position):
            """The named instance is 3, the weeks either side 1, the rest explicitly 0."""
            grades = {}
            for other, doc in enumerate(docs):
                grades[doc.id] = 3 if other == position else 1 if abs(other - position) == 1 else 0
            return grades

        for position in (2, weeks - 4):
            doc = docs[position]
            lib.ask(f"v3-series-owner-{slug}-{position:02d}",
                    f"In week {doc.meta['week']:02d} of the {title.lower()}, who was put down "
                    f"against the drift report action?",
                    "series instance lookup", [NEAR_DUP, MULTI_DOC],
                    graded(position), {doc.id: ["owner"]})
        lib.ask(f"v3-series-latest-{slug}",
                f"In the last recorded session of the {title.lower()}, what date was set "
                f"against the drift report action?",
                "latest value in a series", [NEAR_DUP, SUPERSEDED],
                graded(len(docs) - 1), {docs[-1].id: ["owner"]})
        lib.ask(f"v3-series-reversal-{slug}",
                f"Which proposal did the {title.lower()} back out of, and in which week?",
                "reversed decision", [NEAR_DUP, NEGATION],
                graded(weeks - 3), {docs[weeks - 3].id: ["decision"]})


LONG_PLAN = [
    ("handbook-prose-0", "Platform operations handbook, unpaginated edition", "prose", 52000, "ops"),
    ("handbook-prose-1", "Field service handbook, unpaginated edition", "prose", 47000, "ops"),
    ("handbook-prose-2", "People handbook, continuous text edition", "prose", 44000, "hr"),
    ("handbook-prose-3", "Records and disclosure handbook, continuous text edition",
     "prose", 41000, "hr"),
    ("handbook-tree-0", "Platform operations handbook, structured edition", "tree", 78000, "ops"),
    ("handbook-tree-1", "Security control handbook, structured edition", "tree", 71000, "ops"),
    ("handbook-tree-2", "People handbook, structured edition", "tree", 66000, "hr"),
    ("handbook-tree-3", "Site facilities handbook, structured edition", "tree", 58000, "hr"),
    ("handbook-tree-4", "Change management handbook, structured edition", "tree", 54000, "ops"),
    ("agreement-long-0", "Tessivar Cloud framework agreement, consolidated text",
     "clauses", 84000, "legal"),
    ("agreement-long-1", "Calderwick Freight framework agreement, consolidated text",
     "clauses", 72000, "legal"),
    ("agreement-long-2", "Brackleton Facilities framework agreement, consolidated text",
     "clauses", 61000, "legal"),
    ("transcript-long-0", "Quarterly platform review, full transcript", "transcript", 41000, "meeting"),
    ("transcript-long-1", "Incident long-tail review, full transcript", "transcript", 36000, "meeting"),
    ("transcript-long-2", "Supplier negotiation, full transcript", "transcript", 31000, "meeting"),
    ("transcript-long-3", "All-hands question session, full transcript", "transcript", 27000, "meeting"),
]

STYLE_POOLS = {"ops": D.OPS_SENTENCES, "hr": D.HR_SENTENCES,
               "legal": D.LEGAL_SENTENCES, "meeting": D.MEETING_SENTENCES}
SHAPE_KIND = {"prose": "handbook (no headings)", "tree": "handbook (structured)",
              "clauses": "framework agreement", "transcript": "transcript"}

# One fact per depth slot, so the three queries against a long document are three
# different questions rather than the same question with three answers.
LONG_NEEDLES = {
    "ops": [
        ("release", "The {anchor} rule is the one exception to everything above: a ring running "
                    "{value} has to be drained before any schema move, because the older "
                    "admission path cannot read the new lease format.",
         "Which rule makes a ring stop taking traffic before a schema change, and which build "
         "does it apply to?"),
        ("duration", "Under the {anchor} guard a node that fails two liveness probes in a row is "
                     "held out of rotation for {value}, and it is not let back early even if it "
                     "looks healthy again.",
         "How long is a machine kept out of service after it misses its health checks twice in "
         "a row?"),
        ("signal", "Anything raised against this handbook is filed under the {anchor} heading, "
                   "and the standing reference to put on the ticket is {value}.",
         "What reference goes on a ticket raised against this handbook?"),
    ],
    "hr": [
        ("duration", "Under the {anchor} arrangement somebody who transfers between sites keeps "
                     "their old site's calendar for {value}, after which the receiving site's "
                     "calendar applies in full.",
         "When somebody moves between sites, whose public holidays do they get, and for how "
         "long?"),
        ("duration", "The {anchor} allowance covers time taken to attend a hearing as a witness "
                     "and is capped at {value} in any one year.",
         "Is there paid time for going to a hearing as a witness, and is it limited?"),
        ("date", "The {anchor} undertaking given to the works council lapses on {value}, and "
                 "nothing in this handbook survives it.",
         "Which promise to the works council runs out on a fixed day, and when?"),
    ],
    "legal": [
        ("amount", "The {anchor} cap limits the supplier's aggregate liability for indirect loss "
                   "in any twelve-month period to {value}, and that cap survives termination.",
         "What ceiling applies to the supplier's liability for indirect loss over a year?"),
        ("duration", "The {anchor} step obliges the parties to hold an escalation meeting within "
                     "{value} of a notified dispute before either may commence proceedings.",
         "Before anyone goes to court, is there a meeting they have to hold first, and how soon?"),
        ("date", "The {anchor} option to extend must be exercised on or before {value}, after "
                 "which it falls away and cannot be revived by agreement.",
         "Is there an extension option with a deadline, and what is the deadline?"),
    ],
    "meeting": [
        ("date", "the one date that matters out of all of this is {value} — that is when the "
                 "{anchor} commitment lapses and we lose the option entirely.",
         "Which commitment lapses on a fixed date, and what is that date?"),
        ("duration", "we agreed the {anchor} pause: nobody ships into that ring for {value} "
                     "after a customer-visible failure, regardless of how small the fix looks.",
         "How long is the freeze on shipping after something breaks in front of a customer?"),
        ("release", "for the record, the {anchor} rollback target is {value} and not whatever is "
                    "current at the time — we have got that wrong twice now.",
         "What do we roll back to when this goes wrong, and is it just the previous build?"),
    ],
}


def _transcript_block(rng, speakers, minute):
    lines = []
    for step in range(rng.randint(4, 8)):
        speaker = rng.choice(speakers)
        body = sentence(rng.choice(D.MEETING_SENTENCES + D.OPS_SENTENCES), rng)
        lines.append(f"[{minute // 60:02d}:{minute % 60:02d}:{step * 7 % 60:02d}] {speaker}: {body}")
    return "\n".join(lines)


def build_long(lib):
    rng = rng_for("long")
    for doc_id, title, shape, target, style in LONG_PLAN:
        doc = Doc(id=doc_id, title=title, kind=SHAPE_KIND[shape], collection="work/long-form",
                  effective_date=lib.tokens.date())
        pool = STYLE_POOLS[style]
        doc.add(f"# {title}")
        speakers = [rng.choice(D.POOLS["person"]) for _ in range(5)]
        size, minute, part, section, clause = 0, 9 * 60, 0, 0, 0
        while size < target:
            if shape == "tree":
                if section % 4 == 0:
                    part += 1
                    doc.add(f"## Part {part} — {rng.choice(D.HEADING_PARTS)}")
                section += 1
                doc.add(f"### {section}. {rng.choice(D.HEADING_SECTIONS)}")
                for _ in range(rng.randint(2, 4)):
                    doc.add(f"#### {rng.choice(D.HEADING_SUBS)}")
                    block = paragraph(rng, pool, 4, 7)
                    doc.add(block)
                    size += len(block)
            elif shape == "clauses":
                section += 1
                doc.add(f"## Section {section}. {rng.choice(D.HEADING_PARTS)}")
                for _ in range(rng.randint(3, 6)):
                    clause += 1
                    block = f"{section}.{clause} " + paragraph(rng, pool, 3, 5)
                    doc.add(block)
                    size += len(block)
            elif shape == "transcript":
                block = _transcript_block(rng, speakers, minute)
                minute += rng.randint(2, 6)
                doc.add(block)
                size += len(block)
            else:
                block = paragraph(rng, pool, 6, 10)
                doc.add(block)
                size += len(block)
        doc.meta = {"shape": shape, "style": style}
        lib.add(doc)

    long_docs = [lib.by_id[plan[0]] for plan in LONG_PLAN]
    for order, doc in enumerate(long_docs):
        style = doc.meta["style"]
        for slot, fraction in enumerate((0.12, 0.5, 0.88)):
            value_kind, template, question = LONG_NEEDLES[style][slot]
            anchor = lib.tokens.anchor()
            value = lib.tokens.of_kind(value_kind)
            body = template.replace("{anchor}", anchor).replace("{value}", value)
            if style == "meeting":
                body = f"[{10 + slot:02d}:{order * 3 % 60:02d}:00] " \
                       f"{D.POOLS['person'][order % len(D.POOLS['person'])]}: {body}"
            doc.mark_at(f"needle{slot}", body, max(1, int(len(doc.blocks) * fraction)))
            lib.needle([anchor, value], [doc.id])
            doc.meta[f"question{slot}"] = question

    # Twelve tail needles keep v2's "long-context tail facts" comparable; the rest
    # sit at 12% and 50% depth so oversized chunks cannot be hidden by position.
    asked = [(order, 2) for order in range(len(long_docs)) if order % 4 != 3]
    asked += [(order, 0) for order in range(len(long_docs)) if order % 4 == 3]
    asked += [(1, 1), (9, 1)]
    for order, slot in sorted(asked):
        doc = long_docs[order]
        dimensions = [BURIED, PARAPHRASE]
        if slot == 2:
            dimensions.append(TAIL)
        else:
            dimensions.append(HARD_NEG)
        grades = {other.id: 0 for other in long_docs
                  if other is not doc and other.meta["style"] == doc.meta["style"]}
        grades[doc.id] = 3
        lib.ask(f"v3-buried-{doc.id}-{slot}",
                f"In the {doc.title.lower()}: {doc.meta[f'question{slot}']}",
                "buried needle", dimensions, grades, {doc.id: [f"needle{slot}"]})


CALIBRATION_ROWS = ["Ostrel-7 probe", "Pellum-2 head", "Garnetline gauge", "Sibbe manifold",
                    "Wrackford coupler", "Dunlark sleeve"]


def build_tables(lib):
    rng = rng_for("tables")
    for index in range(9):
        measure = lib.tokens.measure()
        row = CALIBRATION_ROWS[index % len(CALIBRATION_ROWS)]
        doc = Doc(id=f"table-calibration-{index:02d}",
                  title=f"Quorvin Metrology calibration record {index + 1:02d}",
                  kind="calibration record", collection="engineering/records",
                  effective_date=lib.tokens.date())
        doc.add(f"# {doc.title}")
        doc.mark("cell",
                 "| Instrument | Tolerance | Interval | Last pass |\n"
                 "| --- | ---: | ---: | --- |\n"
                 + "\n".join(
                     f"| {name} | {measure if name == row else '0.0999 mm'} | "
                     f"{rng.randint(6, 24)} months | {rng.choice(D.POOLS['month'])} |"
                     for name in CALIBRATION_ROWS))
        doc.add(paragraph(rng, D.OPS_SENTENCES, 3, 5))
        lib.needle([measure], [doc.id])
        lib.add(doc)
        if index < 6:
            lib.ask(f"v3-table-cell-{index:02d}",
                    f"In calibration record {index + 1:02d}, what tolerance is listed against "
                    f"the {row}?",
                    "markdown table cell", [TABLES, IDENTIFIER],
                    {doc.id: 3}, {doc.id: ["cell"]}, exempt=True)

    for index in range(9):
        amount = lib.tokens.amount()
        site = D.POOLS["site"][index % len(D.POOLS["site"])]
        doc = Doc(id=f"table-spend-{index:02d}", title=f"Site spend extract {index + 1:02d}",
                  kind="spend extract", collection="finance/extracts",
                  effective_date=lib.tokens.date())
        doc.add(f"# {doc.title}")
        doc.mark("cell", "site,category,committed,invoiced\n" + "\n".join(
            f"{name},maintenance,{amount if name == site else '£0,000.00'},£0,000.00"
            for name in D.POOLS["site"]))
        doc.add(paragraph(rng, D.HR_SENTENCES, 2, 4))
        lib.needle([amount], [doc.id])
        lib.add(doc)
        if index < 3:
            lib.ask(f"v3-table-csv-{index:02d}",
                    f"In site spend extract {index + 1:02d}, what is the committed maintenance "
                    f"figure for {site}?",
                    "csv cell", [TABLES, IDENTIFIER], {doc.id: 3}, {doc.id: ["cell"]},
                    exempt=True)


def build_chat(lib):
    rng = rng_for("chat")
    for index in range(18):
        doc = Doc(id=f"chatlog-{index:02d}", title=f"On-call room log, session {index + 1:02d}",
                  kind="chat log", collection="work/chat", effective_date=lib.tokens.date())
        doc.add(f"# {doc.title}")
        minute = 8 * 60 + index
        for _ in range(rng.randint(8, 14)):
            block = []
            for _step in range(rng.randint(3, 6)):
                block.append(f"{minute // 60:02d}:{minute % 60:02d} "
                             + fill(rng.choice(D.CHAT_LINES), rng))
                minute += rng.randint(1, 4)
            doc.add("\n".join(block))
        if index < 6:
            code = lib.tokens.error_code()
            anchor = lib.tokens.anchor()
            speaker = rng.choice(D.POOLS["person"])
            doc.mark_at("fact",
                        f"{minute // 60:02d}:{minute % 60:02d} {speaker}: for the record, the "
                        f"{anchor} workaround is what actually cleared it, not the restart — the "
                        f"restart just happened to come next. Filed as {code}.",
                        max(1, len(doc.blocks) // 2))
            lib.needle([anchor, code], [doc.id])
            lib.ask(f"v3-chat-fact-{index:02d}",
                    "Someone in the on-call room pointed out that a reboot got the credit for a "
                    "fix it did not do. What had really sorted it out?",
                    "transcript needle", [NOISY, PARAPHRASE],
                    {doc.id: 3}, {doc.id: ["fact"]})
        lib.add(doc)


SCAN_KINDS = [("scanned minutes", "meeting"), ("scanned manual", "ops"),
              ("scanned notice", "hr"), ("scanned schedule", "legal")]


def build_ocr(lib):
    rng = rng_for("ocr")
    for index in range(22):
        label, style = SCAN_KINDS[index % len(SCAN_KINDS)]
        code = lib.tokens.signal()
        anchor = lib.tokens.anchor()
        doc = Doc(id=f"scan-{index:02d}", title=f"{label.capitalize()} {index + 1:02d} (scanned)",
                  kind=label, collection="archive/scans", effective_date=lib.tokens.date(),
                  separator="")
        clean = [f"# {doc.title}"] + prose(rng, STYLE_POOLS[style], rng.randint(6, 10), 4, 7)
        clean.insert(rng.randint(2, len(clean) - 1),
                     f"Noted for the file: the {anchor} arrangement is why this site keeps stock "
                     f"of its own instead of drawing from the central store, and the reference "
                     f"to quote when ordering against it is {code}.")
        damaged = ocr_damage("\n\n".join(clean), rng, protect=(code, anchor))
        # Page furniture and dropped spaces move every offset, so the needle span is
        # recovered from the damaged text rather than assumed from the clean one.
        start, end = damaged.index(anchor), damaged.index(code) + len(code)
        doc.blocks = [damaged[:start], damaged[start:end], damaged[end:]]
        doc.marks["fact"] = 1
        lib.needle([anchor, code], [doc.id])
        lib.add(doc)

    scans = lib.pick("scan-")
    for index, doc in enumerate(scans[:5]):
        lib.ask(f"v3-ocr-code-{index:02d}",
                f"What reference is quoted when ordering against the local stock arrangement in "
                f"{doc.title.lower()}?",
                "identifier in a damaged scan", [NOISY, IDENTIFIER],
                {doc.id: 3}, {doc.id: ["fact"]})
    for index, doc in enumerate(scans[5:10]):
        lib.ask(f"v3-ocr-reason-{index:02d}",
                f"One scanned file explains why a site holds its own stock rather than drawing "
                f"from the central store. Which arrangement does {doc.title.lower()} name?",
                "fact in a damaged scan", [NOISY, PARAPHRASE],
                {doc.id: 3}, {doc.id: ["fact"]})


def build_personal(lib):
    rng = rng_for("personal")
    for index in range(30):
        doc = Doc(id=f"journal-{index:02d}", title=f"Journal, entry {index + 1:02d}",
                  kind="journal entry", collection="personal/journal",
                  effective_date=lib.tokens.date())
        doc.add(f"# {doc.title}")
        doc.extend(prose(rng, D.JOURNAL_SENTENCES, rng.randint(3, 5), 3, 6))
        lib.add(doc)
    for index in range(24):
        author = D.POOLS["author"][index % len(D.POOLS["author"])]
        field_name = D.POOLS["field"][index % len(D.POOLS["field"])]
        doc = Doc(id=f"reading-{index:02d}", title=f"Reading notes: {author} on {field_name}",
                  kind="reading notes", collection="personal/reading",
                  effective_date=lib.tokens.date())
        doc.add(f"# {doc.title}")
        doc.extend(prose(rng, D.READING_SENTENCES, rng.randint(3, 5), 3, 6))
        lib.add(doc)
    for index in range(20):
        dish = D.POOLS["dish"][index % len(D.POOLS["dish"])].replace("the ", "")
        doc = Doc(id=f"recipe-{index:02d}",
                  title=f"Recipe: {dish} with {D.POOLS['ingredient'][index % 12]}",
                  kind="recipe", collection="personal/recipes")
        doc.add(f"# {doc.title}")
        doc.add("## Method\n" + paragraph(rng, D.RECIPE_SENTENCES, 4, 6))
        doc.extend(prose(rng, D.RECIPE_SENTENCES, rng.randint(1, 3), 3, 5))
        lib.add(doc)
    for index in range(24):
        doc = Doc(id=f"home-{index:02d}", title=f"{D.HOUSE}: maintenance log {index + 1:02d}",
                  kind="maintenance log", collection="personal/home",
                  effective_date=lib.tokens.date())
        doc.add(f"# {doc.title}")
        doc.extend(prose(rng, D.HOME_SENTENCES, rng.randint(2, 4), 3, 5))
        lib.add(doc)


COLLISIONS = [
    ("Garnetline", "the Garnetline migration at Quillon Grid",
     "the Garnetline footpath along the reservoir",
     "the Garnetline Building, a Brackleton Facilities refurbishment"),
    ("Ostrel", "the Ostrel telemetry product",
     "Ostrel blue, a washed-rind cheese used in two recipes",
     "Ostrel Row, the street the Aldersgate Print works stands on"),
    ("Sibbe", "the Sibbe service at Quillon Grid",
     "the Sibbes at number twelve, the neighbours at Tanmoor Row",
     "Sibbe and Ollmarch, the authors of a paper on failure taxonomy"),
    ("Dunlark", "the Dunlark pilot at Quillon Grid",
     "Dunlark, a braised dish learned from a market stall",
     "Dunlark Wharf, where the Port Ammerly depot stands"),
]

COLLISION_SLOTS = [("work", "project brief", "work/projects", "ops"),
                   ("personal", "note", "personal/notes", "meeting"),
                   ("third", "note", "work/facilities", "hr")]


def build_collisions(lib):
    rng = rng_for("collisions")
    for name, *descriptions in COLLISIONS:
        family = []
        for (suffix, kind, collection, style), description in zip(COLLISION_SLOTS, descriptions):
            anchor = lib.tokens.anchor()
            value = lib.tokens.date()
            doc = Doc(id=f"collision-{name.lower()}-{suffix}", title=f"{name}: {description}",
                      kind=kind, collection=collection, effective_date=lib.tokens.date())
            doc.add(f"# {doc.title}")
            # The description stays in the title; repeating it here would let a
            # query quote its own answer passage.
            doc.mark("fact", f"The {anchor} milestone falls on {value}. Three unrelated things "
                             f"in this library are called {name}, and only this one has that "
                             f"milestone.")
            doc.extend(prose(rng, STYLE_POOLS[style], rng.randint(2, 4), 3, 5))
            lib.needle([anchor, value], [doc.id])
            lib.add(doc)
            family.append((doc, description))
        for position, (doc, description) in enumerate(family):
            grades = {other.id: 0 for other, _ in family if other is not doc}
            grades[doc.id] = 3
            lib.ask(f"v3-collision-{name.lower()}-{position}",
                    f"Three different things in here are called {name}. Which milestone date "
                    f"belongs to {description}?",
                    "codename collision", [COLLISION, HARD_NEG], grades, {doc.id: ["fact"]})


FRAGMENTS = [
    ("stopcock", "the stopcock at {HOUSE} is under the sink boards, not in the cupboard",
     "Where is the water shut-off in the house?"),
    ("meter-reading", "the electricity meter is behind the hatch in the front hall",
     "Where do I find the electricity meter?"),
    ("loft-hatch", "the loft hatch pole lives behind the coats", "How do I get up into the loft?"),
    ("boiler-reset", "the boiler resets by holding the middle button for ten seconds",
     "How is the boiler restarted?"),
    ("bin-day", "recycling goes out on the Tuesday before the first Wednesday",
     "Which day does the recycling go out?"),
    ("ferry", "the last ferry back from Port Ammerly is earlier on Sundays",
     "Is the final boat from Port Ammerly different at the weekend?"),
    ("bread", "the bread wants less water than the book says in a cold kitchen",
     "Why does the loaf come out sticky in winter?"),
    ("coffee", "the grinder setting drifts coarser as the burrs warm up",
     "Why does the coffee change partway through a session?"),
    ("pager", "the pager escalation goes to the bench, never to a person's mobile",
     "Does being on call ever mean a personal phone rings?"),
    ("badge", "the badge reader by the loading bay is the only one that reads a worn card",
     "Which entry point still works with a scratched pass?"),
    ("charger", "the spare laptop charger is in the drawer under the printer",
     "Where is the second power supply kept?"),
    ("shed-key", "the shed key is on the ring with the red tag, not the green one",
     "Which key opens the shed?"),
]


def build_fragments(lib):
    rng = rng_for("fragments")
    fragments = []
    for index, (slug, sentence, _question) in enumerate(FRAGMENTS):
        anchor = lib.tokens.anchor()
        doc = Doc(id=f"fragment-{slug}", title=slug.replace("-", " ").capitalize(),
                  kind="fragment note", collection="personal/fragments")
        link = FRAGMENTS[(index + 1) % len(FRAGMENTS)][0].replace("-", " ").capitalize()
        doc.mark("fact", f"# {doc.title}\n{sentence.replace('{HOUSE}', D.HOUSE)} — "
                         f"{anchor} confirmed it. See [[{link}]].")
        lib.needle([anchor], [doc.id])
        lib.add(doc)
        fragments.append(doc)

    # Long notes that mention every topic and answer none of them, so a fragment
    # has to win on being the actual answer rather than on sharing a word.
    for index in range(12):
        doc = Doc(id=f"fragment-decoy-{index:02d}",
                  title=f"House and office notes, long entry {index + 1:02d}",
                  kind="notes", collection="personal/notes", effective_date=lib.tokens.date())
        doc.add(f"# {doc.title}")
        doc.add("Mentioned in passing and nowhere explained: the stopcock, the electricity "
                "meter, the loft hatch, the boiler, the recycling, the ferry, the bread, the "
                "grinder, the pager, the badge reader, the spare charger and the shed key.")
        doc.extend(prose(rng, D.HOME_SENTENCES + D.JOURNAL_SENTENCES, rng.randint(4, 7), 4, 7))
        lib.add(doc)

    decoys = {f"fragment-decoy-{index:02d}": 0 for index in range(12)}
    for index, (doc, (_slug, _sentence, question)) in enumerate(zip(fragments, FRAGMENTS)):
        grades = dict(decoys)
        grades[doc.id] = 3
        lib.ask(f"v3-fragment-{index:02d}", question, "fragment beats a long mention",
                [FRAGMENT, HARD_NEG], grades, {doc.id: ["fact"]})


def build_multihop(lib):
    rng = rng_for("multihop")
    contracts = lib.pick("contract-", lambda d: d.meta.get("vendor"))
    briefs = []
    for index, contract in enumerate(contracts):
        project = contract.meta["project"]
        anchor = lib.tokens.anchor()
        brief = Doc(id=f"project-brief-{index:02d}", title=f"Project brief: {project}",
                    kind="project brief", collection="work/projects",
                    effective_date=lib.tokens.date())
        brief.add(f"# Project brief: {project}")
        brief.mark("link", f"## Supply\nLogistics and on-site handling run through "
                           f"{contract.meta['vendor']} under the {anchor} workstream. No other "
                           f"supplier is engaged here.")
        brief.extend(prose(rng, D.OPS_SENTENCES, rng.randint(3, 5), 4, 6))
        lib.needle([anchor], [brief.id])
        brief.meta = {"project": project, "vendor": contract.meta["vendor"]}
        lib.add(brief)
        briefs.append(brief)
        if index < 4:
            lib.ask(f"v3-multihop-renewal-{index:02d}",
                    f"The supplier handling logistics for {project} — when does its master "
                    f"agreement come up for renewal?",
                    "two-document composition", [MULTIHOP, MULTI_DOC],
                    {brief.id: 3, contract.id: 3},
                    {brief.id: ["link"], contract.id: ["renewal"]})
        else:
            lib.ask(f"v3-multihop-notice-{index:02d}",
                    f"How much notice would we have to give to end the contract of whoever does "
                    f"on-site work for {project}?",
                    "two-document composition", [MULTIHOP, MULTI_DOC],
                    {brief.id: 3, contract.id: 3},
                    {brief.id: ["link"], contract.id: ["renewal"]})

    orders = lib.pick("purchase-order-")
    for index in range(4):
        order = orders[index * 3]
        contract = next(d for d in contracts if d.meta["vendor"] == order.meta["vendor"])
        lib.ask(f"v3-multihop-part-{index:02d}",
                f"Which supplier's framework covers the order carrying part "
                f"{order.meta['part']}, and what is the withdrawal undertaking in it called?",
                "two-document composition", [MULTIHOP, MULTI_DOC, IDENTIFIER],
                {order.id: 3, contract.id: 3},
                {order.id: ["line"], contract.id: ["clause"]}, exempt=True)


VAL_SLOT = re.compile(r"\{val(?::(\w+))?\}")


def build_paraphrase(lib):
    rng = rng_for("paraphrase")
    hosts = {
        "policy": lib.pick("policy-", lambda d: d.id.endswith("-v3")),
        "runbook": lib.pick("runbook-core-"),
        "contract": lib.pick("contract-", lambda d: d.meta.get("vendor")),
    }
    used = {key: 0 for key in hosts}
    for index, item in enumerate(D.PARAPHRASE_FACTS):
        pool = hosts[item["host"]]
        host = pool[used[item["host"]] % len(pool)]
        decoy = pool[(used[item["host"]] + 3) % len(pool)]
        used[item["host"]] += 1
        anchor = lib.tokens.anchor()
        match = VAL_SLOT.search(item["statement"])
        value = lib.tokens.of_kind(match.group(1) or "duration")
        statement = VAL_SLOT.sub(value.replace("\\", r"\\"),
                                 item["statement"].replace("{anchor}", anchor))
        key = f"para{index}"
        host.mark_at(key, "## Standing provision\n" + statement, max(1, len(host.blocks) // 3))
        decoy.mark_at(f"decoy{index}", "## Standing provision\n" + fill(item["decoy"], rng),
                      max(1, len(decoy.blocks) // 3))
        lib.needle([anchor, value], [host.id])
        lib.ask(f"v3-paraphrase-{index:02d}", item["question"], "vocabulary mismatch",
                [PARAPHRASE, HARD_NEG], {host.id: 3, decoy.id: 0}, {host.id: [key]})


MULTILINGUAL_ASK = ["intl-de-schluessel", "intl-es-transporte", "intl-es-repuestos",
                    "intl-ru-kalibrovka", "intl-ja-yobikagi", "intl-ja-haisenzu",
                    "intl-zh-yanshou", "intl-zh-beiyongbeng"]


def build_multilingual(lib):
    for entry in D.MULTILINGUAL:
        doc = Doc(id=entry["id"], title=entry["title"], kind=entry["kind"],
                  collection="work/international", language=entry["language"])
        for block in entry["text"].split("\n\n"):
            if entry["token"] in block and "fact" not in doc.marks:
                doc.mark("fact", block)
            else:
                doc.add(block)
        if "fact" not in doc.marks:
            raise ValueError(f"{entry['id']}: token missing from the document body")
        lib.needle([entry["token"]], [doc.id])
        lib.add(doc)

    for index, entry in enumerate(D.MULTILINGUAL):
        if entry["id"] not in MULTILINGUAL_ASK:
            continue
        siblings = {other["id"]: 0 for other in D.MULTILINGUAL
                    if other["language"] == entry["language"] and other["id"] != entry["id"]}
        for position, query in enumerate(entry["queries"]):
            grades = dict(siblings)
            grades[entry["id"]] = 3
            dimensions = [MULTILINGUAL, HARD_NEG]
            category = "same-language" if query["lang"] == entry["language"] else "cross-lingual"
            if len(query["text"]) <= 4:
                dimensions.append(FRAGMENT)
                category = "short CJK query"
            lib.ask(f"v3-intl-{index:02d}-{position}", query["text"], category, dimensions,
                    grades, {entry["id"]: ["fact"]}, exempt=True)


UNANSWERABLE = [
    ("bare-code", "{err}", "identifier that does not exist"),
    ("code-sentence", "Which runbook covers {err}, and who is paged for it?",
     "identifier that does not exist"),
    ("order", "What was the unit price on purchase order {po}?",
     "identifier that does not exist"),
    ("ticket", "Which incident does {tck} refer to?", "identifier that does not exist"),
    ("part", "Which supplier ships part {part}?", "identifier that does not exist"),
    ("signal", "What was recorded against {sig}?", "identifier that does not exist"),
    ("release", "Which handbook says a ring running {rel} has to be drained?",
     "identifier that does not exist"),
    ("scheduled", "What is scheduled for {date}?", "identifier that does not exist"),
    ("clause-a", "Which vendor is covered by the {a0} exception?", "named rule that does not exist"),
    ("clause-b", "What does the {a1} undertaking oblige the supplier to do?",
     "named rule that does not exist"),
    ("clause-c", "How long does the {a2} allowance last?", "named rule that does not exist"),
    ("clause-d", "Which site does the {a3} addendum apply to?", "named rule that does not exist"),
    ("clause-e", "Who sits on the {a4} committee?", "named rule that does not exist"),
    ("clause-f", "What is the cap under the {a5} provision?", "named rule that does not exist"),
    ("clause-g", "Which runbook describes the {a6} guard?", "named rule that does not exist"),
    ("clause-h", "When does the {a7} commitment lapse?", "named rule that does not exist"),
    ("address", "What is Marisol Quenby's home address?", "attribute the vault never records"),
    ("salary", "What is Tobin Hafflin's salary band this year?",
     "attribute the vault never records"),
    ("password", "What is the password for the Nyelle escalation queue?",
     "attribute the vault never records"),
    ("mobile", "What is the mobile number for the Sepwick field crew lead?",
     "attribute the vault never records"),
    ("repair-cost", "How much did the boiler repair at 14 Tanmoor Row cost?",
     "attribute the vault never records"),
]

MISSING = {"err": "ERR-0001", "po": "PO-00001", "tck": "TCK-0001", "part": "QG-000-001",
           "sig": "SIG-00001", "rel": "v1.0.1", "date": "2099-12-31",
           "a0": "Zennerloft", "a1": "Marbleau", "a2": "Quinstock", "a3": "Verrowfen",
           "a4": "Hastermill", "a5": "Oddingbrae", "a6": "Pilcrane", "a7": "Tullowmere"}
NEVER_PRESENT = ["home address", "salary band", "password", "mobile number", "repair cost",
                 "bank details"]


def build_unanswerable(lib):
    lib.absent.extend(sorted(MISSING.values()) + NEVER_PRESENT)
    for slug, template, category in UNANSWERABLE:
        text = template
        for name, value in MISSING.items():
            text = text.replace("{" + name + "}", value)
        lib.ask(f"v3-unanswerable-{slug}", text, category, [UNANSWERABLE_TAG, HARD_NEG], {})


# --- integrity ----------------------------------------------------------------

def check_integrity(lib):
    texts = [(doc.id, doc.text) for doc in lib.docs]
    problems = []

    for needle in lib.needles:
        for token in needle["tokens"]:
            found = sorted(doc_id for doc_id, text in texts if token in text)
            if found != needle["docs"]:
                problems.append(
                    f"needle {token!r} appears in {found} but was declared for {needle['docs']}")

    for token in lib.absent:
        found = sorted(doc_id for doc_id, text in texts if token in text)
        if found:
            problems.append(f"unanswerable token {token!r} leaked into {found}")

    known = set(lib.by_id)
    for query in lib.queries:
        positives = {doc for doc, grade in query["relevance"].items() if grade > 0}
        if not set(query["relevance"]).issubset(known):
            problems.append(f"{query['id']}: labels reference unknown documents")
        if not set(query["spans"]).issubset(positives):
            problems.append(f"{query['id']}: answer spans outside the relevant documents")
        if positives and not query["spans"]:
            problems.append(f"{query['id']}: answerable query without an answer span")
        if len(positives) > 3:
            problems.append(f"{query['id']}: more positives than recall@5 can reward")
        for dimension in query["dimensions"] or ["<none>"]:
            if dimension not in DIMENSIONS:
                problems.append(f"{query['id']}: unknown dimension {dimension!r}")
        if query["exempt"]:
            continue
        for doc_id, keys in query["spans"].items():
            passage = " ".join(lib.by_id[doc_id].passage(key) for key in keys)
            text = query["text"]
            quoted = next((text[at:at + MAX_QUOTED_CHARACTERS]
                           for at in range(len(text) - MAX_QUOTED_CHARACTERS + 1)
                           if text[at:at + MAX_QUOTED_CHARACTERS] in passage), None)
            if quoted:
                problems.append(f"{query['id']}: quotes its own answer ({quoted!r})")

    counts = {}
    for query in lib.queries:
        for dimension in query["dimensions"]:
            counts[dimension] = counts.get(dimension, 0) + 1
    for dimension in DIMENSIONS:
        if counts.get(dimension, 0) < MIN_PER_DIMENSION:
            problems.append(f"dimension {dimension!r} has {counts.get(dimension, 0)} queries, "
                            f"needs {MIN_PER_DIMENSION}")
    if not 150 <= len(lib.queries) <= 200:
        problems.append(f"{len(lib.queries)} queries, wanted between 150 and 200")
    if not 300 <= len(lib.docs) <= 400:
        problems.append(f"{len(lib.docs)} documents, wanted between 300 and 400")

    if problems:
        raise ValueError("fixture integrity failed:\n  " + "\n  ".join(problems))
    return counts


def check_spans(dataset):
    """Every answer span must decode and must sit inside its own document."""
    bodies = {doc["id"]: doc["text"].encode("utf-8") for doc in dataset["documents"]}
    for query in dataset["queries"]:
        for doc_id, spans in query.get("answer_spans", {}).items():
            body = bodies[doc_id]
            for start, end in spans:
                if not 0 <= start < end <= len(body):
                    raise ValueError(f"{query['id']}: span out of range in {doc_id}")
                body[start:end].decode("utf-8")


def build():
    lib = Library()
    build_runbooks(lib)
    build_policies(lib)
    build_vendors(lib)
    build_meetings(lib)
    build_long(lib)
    build_tables(lib)
    build_chat(lib)
    build_ocr(lib)
    build_personal(lib)
    build_collisions(lib)
    build_fragments(lib)
    build_multilingual(lib)
    build_multihop(lib)
    build_paraphrase(lib)
    build_unanswerable(lib)
    lib.finalize()
    check_integrity(lib)
    dataset = lib.dataset()
    validate_dataset(dataset)
    check_spans(dataset)
    unique_records(dataset["documents"], "id")
    unique_records(dataset["queries"], "id")
    digest(dataset)
    return dataset


def render(dataset):
    return json.dumps(dataset, indent=2, ensure_ascii=False, allow_nan=False) + "\n"


def summary(dataset):
    counts = {}
    for query in dataset["queries"]:
        for dimension in query["dimensions"]:
            counts[dimension] = counts.get(dimension, 0) + 1
    return {
        "documents": len(dataset["documents"]),
        "queries": len(dataset["queries"]),
        "unanswerable_queries": sum(1 for q in dataset["queries"] if not q["relevance"]),
        "total_characters": sum(len(doc["text"]) for doc in dataset["documents"]),
        "longest_document_characters": max(len(d["text"]) for d in dataset["documents"]),
        "queries_per_dimension": dict(sorted(counts.items())),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed fixture differs from a fresh build")
    args = parser.parse_args()
    dataset = build()
    text = render(dataset)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != text:
            raise SystemExit(f"{args.output} is stale; re-run this script without --check")
    else:
        args.output.write_text(text, encoding="utf-8")
        import validate_rag_evals
        validate_rag_evals.main()
    print(json.dumps(summary(dataset), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
